INSERT INTO library_contents
(id,title,slug,excerpt,body,type,category,tags,author,status,published_at,flags,visibility,sale_enabled,price,currency,book_format,page_count,display_priority)
VALUES
('8f100000-0000-4000-8000-000000000001','Free Project Kickoff Checklist','free-project-kickoff-checklist','A practical checklist for preparing and running a focused project kickoff.','Use this checklist to confirm the business objective, approved scope, sponsor, delivery team, roles, governance, milestones, assumptions, risks, communications, controls, and immediate next actions before the project begins.','checklist','Project Management',JSON_ARRAY('free resource','kickoff','governance','planning'),'PCMO Publications','published',NOW(),JSON_OBJECT('featured',true,'recommended',true),JSON_OBJECT('library',true,'image',true,'author',true,'dates',true,'tags',true,'attachments',true,'downloads',true,'comments',true,'sharing',true,'repost',true,'membership',JSON_ARRAY('free','paid')),FALSE,0,'USD','Digital guide',12,100),
('8f100000-0000-4000-8000-000000000002','Free Contract Notice Writing Guide','free-contract-notice-writing-guide','Clear guidance for preparing timely, factual, and contract-aware notices.','A good contract notice identifies the relevant event, contractual basis, known facts, dates, potential effect, required response, reservations, and supporting records. Always check the governing contract and obtain appropriate professional advice for material matters.','guide','Contract Management',JSON_ARRAY('free resource','contracts','notice','records'),'PCMO Publications','published',NOW(),JSON_OBJECT('featured',true),JSON_OBJECT('library',true,'image',true,'author',true,'dates',true,'tags',true,'attachments',true,'downloads',true,'comments',true,'sharing',true,'repost',true,'membership',JSON_ARRAY('free','paid')),FALSE,0,'USD','Digital guide',16,95),
('8f100000-0000-4000-8000-000000000003','Free Risk Review Meeting Template','free-risk-review-meeting-template','A repeatable agenda for productive project and contract risk reviews.','Structure the meeting around changed context, new threats and opportunities, control effectiveness, action ownership, due dates, escalation thresholds, contingency readiness, contractual exposure, decisions, and updates required in the risk register.','template','Risk Management',JSON_ARRAY('free resource','risk','meeting','template'),'PCMO Publications','published',NOW(),JSON_OBJECT('recommended',true),JSON_OBJECT('library',true,'image',true,'author',true,'dates',true,'tags',true,'attachments',true,'downloads',true,'comments',true,'sharing',true,'repost',true,'membership',JSON_ARRAY('free','paid')),FALSE,0,'USD','Editable template',8,90),
('8f100000-0000-4000-8000-000000000004','Free Stakeholder Communication Planner','free-stakeholder-communication-planner','Plan the right message, owner, channel, timing, and feedback route for each stakeholder.','Map stakeholder interest and influence, define the communication objective, identify the responsible communicator, choose an appropriate channel and frequency, document sensitivities, and record how feedback and decisions will be captured.','worksheet','Leadership',JSON_ARRAY('free resource','stakeholders','communication','leadership'),'PCMO Publications','published',NOW(),JSON_OBJECT('popular',true),JSON_OBJECT('library',true,'image',true,'author',true,'dates',true,'tags',true,'attachments',true,'downloads',true,'comments',true,'sharing',true,'repost',true,'membership',JSON_ARRAY('free','paid')),FALSE,0,'USD','Digital worksheet',10,85),
('8f100000-0000-4000-8000-000000000005','Free Change Control Quick Reference','free-change-control-quick-reference','A concise reference for evaluating, approving, implementing, and closing changes.','Record the proposed change and reason, assess scope, schedule, cost, quality, risk, benefits, resources, interfaces, and contract implications, obtain the correct approval, update controlled baselines, communicate the decision, verify implementation, and retain evidence.','reference','Change Management',JSON_ARRAY('free resource','change control','baseline','approval'),'PCMO Publications','published',NOW(),JSON_OBJECT('trending',true),JSON_OBJECT('library',true,'image',true,'author',true,'dates',true,'tags',true,'attachments',true,'downloads',true,'comments',true,'sharing',true,'repost',true,'membership',JSON_ARRAY('free','paid')),FALSE,0,'USD','Quick reference',14,80)
ON DUPLICATE KEY UPDATE
title=VALUES(title),excerpt=VALUES(excerpt),body=VALUES(body),type=VALUES(type),category=VALUES(category),tags=VALUES(tags),author=VALUES(author),status='published',published_at=VALUES(published_at),flags=VALUES(flags),visibility=VALUES(visibility),sale_enabled=FALSE,price=0,currency=VALUES(currency),book_format=VALUES(book_format),page_count=VALUES(page_count),display_priority=VALUES(display_priority);
