CREATE TABLE IF NOT EXISTS website_pages (
  id CHAR(36) PRIMARY KEY, page_group ENUM('primary','additional') NOT NULL DEFAULT 'primary',
  title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL UNIQUE, menu_label VARCHAR(120), summary TEXT, body LONGTEXT,
  hero_image TEXT, call_to_action_label VARCHAR(120), call_to_action_url TEXT, seo_title VARCHAR(255), seo_description TEXT, reference_url TEXT, reference_image_url TEXT,
  status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft', sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_website_pages_group_status (page_group, status), KEY idx_website_pages_sort (sort_order)
);

INSERT IGNORE INTO website_pages (id, page_group, title, slug, menu_label, summary, body, status, sort_order) VALUES
(UUID(),'primary','About PCMO','about','About','Learn about PCMO, its professional community, and its commitment to project and contract management excellence.','PCMO brings together project and contract management professionals through learning, certification, membership, knowledge sharing, and professional networking. Use the admin Content section to expand this page with the organisation’s mission, vision, governance, and history.','published',10),
(UUID(),'primary','Membership & Networking','membership_and_networking','Membership','Build professional connections, access member resources, and participate in the PCMO community.','PCMO membership supports continuous professional development, peer networking, knowledge exchange, and access to member opportunities.','published',20),
(UUID(),'primary','Membership Community','membership_community','Community','Connect with a global community of project and contract management professionals.','Participate in member discussions, professional groups, shared learning, events, and collaborative opportunities across the PCMO community.','published',30),
(UUID(),'primary','Job Community','job_community','Jobs','Discover professional opportunities and career resources for the PCMO community.','Explore career opportunities, professional development resources, and connections relevant to project and contract management.','published',40),
(UUID(),'primary','Podcasts','podcasts','Podcasts','Listen to practical conversations and professional insights from the PCMO community.','PCMO podcasts feature discussions on project delivery, contracts, leadership, risk, claims, procurement, and emerging industry practices.','published',50),
(UUID(),'primary','Webinars','webinars','Webinars','Join expert-led online learning sessions and professional discussions.','Explore webinars designed to share current practice, practical lessons, and specialist knowledge with the PCMO community.','published',60),
(UUID(),'primary','Events','events','Events','Discover upcoming PCMO learning, networking, and professional events.','View professional events that connect members with experts, peers, learning opportunities, and industry conversations.','published',70),
(UUID(),'primary','Certifications','certifications','Certifications','Explore professional certification pathways for project and contract management.','PCMO certifications help professionals demonstrate knowledge, strengthen capabilities, and support continued career development.','published',80),
(UUID(),'primary','Membership Packages','membership_packages','Membership Packages','Compare membership options designed for professionals, students, groups, and organisations.','Review available membership options and choose the pathway that best matches your professional stage and organisational needs.','published',90),
(UUID(),'additional','Membership FAQ','membership_faq','Membership FAQ','Answers to common questions about PCMO membership.','Find guidance about eligibility, membership benefits, account access, renewals, and participation in the PCMO community.','published',10),
(UUID(),'additional','Individual Membership','individual_membership','Individual Membership','Membership for individual project and contract management professionals.','Access professional learning, networking, member resources, and community opportunities through individual membership.','published',20),
(UUID(),'additional','Student Membership','student_membership','Student Membership','Start building professional knowledge and connections while studying.','Student membership supports early career development through learning resources, community access, and professional networking.','published',30),
(UUID(),'additional','Group Membership','group_membership','Group Membership','Connect teams and professional groups with PCMO resources and learning.','Group membership provides a structured way for multiple professionals to access community, knowledge, and development opportunities.','published',40),
(UUID(),'additional','Corporate Membership','corporate_membership','Corporate Membership','Support organisational capability through professional membership and development.','Corporate membership helps organisations connect teams with PCMO learning, knowledge, certification, and professional networks.','published',50),
(UUID(),'additional','Retiree Membership','retiree_membership','Retiree Membership','Remain connected and share professional experience with the PCMO community.','Retiree membership enables experienced professionals to continue learning, networking, mentoring, and contributing to the profession.','published',60),
(UUID(),'additional','Frequently Asked Questions','faqs','FAQs','Find answers to common questions about PCMO services and participation.','Use this page to maintain clear answers about membership, certifications, learning, events, accounts, and support.','published',70),
(UUID(),'additional','Privacy Policy','privacy','Privacy','How PCMO handles and protects personal information.','Use the admin Content section to publish the approved PCMO privacy policy, including data collection, processing, retention, user rights, cookies, and contact details.','draft',80),
(UUID(),'additional','Terms and Conditions','terms','Terms','Terms governing use of PCMO services and digital platforms.','Use the admin Content section to publish the approved legal terms covering accounts, acceptable use, intellectual property, payments, cancellations, and liability.','draft',90);
