INSERT INTO library_contents
(id,title,slug,excerpt,body,type,category,tags,author,status,published_at,flags,visibility,sale_enabled,price,currency,book_format,page_count,display_priority)
VALUES
('8f300000-0000-4000-8000-000000000001','Webinar: Building Credible Project Forecasts','webinar-building-credible-project-forecasts','An expert-led webinar on assumptions, trends, uncertainty, and forecast confidence.','This webinar explores the evidence behind credible schedule and cost forecasts, including baseline quality, progress measurement, assumptions, risk, scenarios, corrective action, and executive communication.','webinar','Project Controls',JSON_ARRAY('free resource','webinar','forecasting'),'PCMO Webinars','published',NOW(),JSON_OBJECT('featured',true),JSON_OBJECT('library',true,'membership',JSON_ARRAY('free','paid')),FALSE,0,'USD','Streaming webinar',1,68),
('8f300000-0000-4000-8000-000000000002','Podcast: Contract Administration under Pressure','podcast-contract-administration-under-pressure','A professional conversation about notices, records, relationships, and timely decisions.','Experienced practitioners discuss how contract teams maintain discipline during delivery pressure without losing collaboration, contractual awareness, reliable records, or escalation clarity.','podcast','Contract Management',JSON_ARRAY('free resource','podcast','contract administration'),'PCMO Podcasts','published',NOW(),JSON_OBJECT('popular',true),JSON_OBJECT('library',true,'membership',JSON_ARRAY('free','paid')),FALSE,0,'USD','Podcast audio',1,67),
('8f300000-0000-4000-8000-000000000003','Video: Understanding the Project Lifecycle','video-understanding-project-lifecycle','A concise visual introduction to project phases, decisions, controls, and outcomes.','The video follows a project from concept and business case through initiation, planning, delivery, transition, closeout, benefits review, and lessons learned.','video','Project Management',JSON_ARRAY('free resource','video','project lifecycle'),'PCMO Learning','published',NOW(),JSON_OBJECT('recommended',true),JSON_OBJECT('library',true,'membership',JSON_ARRAY('free','paid')),FALSE,0,'USD','Streaming video',1,66),
('8f300000-0000-4000-8000-000000000004','Event Recording: Future of Project and Contract Practice','event-recording-future-project-contract-practice','A recorded PCMO panel on digital change, capability, governance, and professional responsibility.','The panel considers AI-assisted decisions, integrated project and contract data, evolving professional skills, responsible innovation, assurance, and future learning priorities.','event recording','Future Practice',JSON_ARRAY('free resource','event recording','future practice'),'PCMO Events','published',NOW(),JSON_OBJECT('trending',true),JSON_OBJECT('library',true,'membership',JSON_ARRAY('free','paid')),FALSE,0,'USD','Event recording',1,65),
('8f300000-0000-4000-8000-000000000005','Audio Briefing: Five Principles of Change Control','audio-briefing-change-control-principles','A short audio briefing for professionals managing project and contract change.','The briefing covers definition, impact assessment, authority, baseline integrity, contractual implications, communication, implementation evidence, and closure.','audio','Change Management',JSON_ARRAY('free resource','audio','change control'),'PCMO Audio Briefings','published',NOW(),JSON_OBJECT(),JSON_OBJECT('library',true,'membership',JSON_ARRAY('free','paid')),FALSE,0,'USD','Audio briefing',1,64),
('8f300000-0000-4000-8000-000000000006','Presentation: Executive Project Governance Essentials','presentation-executive-project-governance','A presentation on sponsorship, decision rights, tolerances, stage gates, and assurance.','This presentation helps leaders clarify accountability, governance forums, escalation thresholds, decision evidence, benefits oversight, risk appetite, and independent assurance.','presentation','Governance',JSON_ARRAY('free resource','presentation','governance'),'PCMO Standards','published',NOW(),JSON_OBJECT(),JSON_OBJECT('library',true,'membership',JSON_ARRAY('free','paid')),FALSE,0,'USD','Presentation',28,63),
('8f300000-0000-4000-8000-000000000007','Infographic: Contract Management Lifecycle','infographic-contract-management-lifecycle','A visual map from strategy and formation through administration and closeout.','The infographic connects contract strategy, market engagement, formation, mobilisation, obligations, performance, change, payment, claims, relationships, compliance, records, and closeout.','infographic','Contract Management',JSON_ARRAY('free resource','infographic','contract lifecycle'),'PCMO Design Studio','published',NOW(),JSON_OBJECT('featured',true),JSON_OBJECT('library',true,'membership',JSON_ARRAY('free','paid')),FALSE,0,'USD','Infographic',1,62),
('8f300000-0000-4000-8000-000000000008','Research Paper: Integrated Project and Contract Controls','research-paper-integrated-controls','An evidence-led examination of connected delivery, commercial, and contract information.','The paper examines how scope, schedule, cost, risk, change, obligations, notices, supplier performance, claims exposure, and forecasting can form a more reliable integrated control environment.','research paper','Research',JSON_ARRAY('free resource','research paper','integrated controls'),'PCMO Research','published',NOW(),JSON_OBJECT('recommended',true),JSON_OBJECT('library',true,'membership',JSON_ARRAY('free','paid')),FALSE,0,'USD','Research paper',36,61),
('8f300000-0000-4000-8000-000000000009','White Paper: Responsible AI in Professional Decisions','white-paper-responsible-ai-decisions','A practical governance position for AI use in project and contract environments.','The white paper addresses human accountability, approved use cases, data protection, confidentiality, validation, explainability, bias, record keeping, professional judgement, escalation, and continual monitoring.','white paper','Digital Practice',JSON_ARRAY('free resource','white paper','responsible AI'),'PCMO Thought Leadership','published',NOW(),JSON_OBJECT('trending',true),JSON_OBJECT('library',true,'membership',JSON_ARRAY('free','paid')),FALSE,0,'USD','White paper',30,60),
('8f300000-0000-4000-8000-000000000010','PCMO Practice Standard: Controlled Professional Decisions','pcmo-practice-standard-controlled-decisions','A practice standard for accountable, evidence-based project and contract decisions.','The standard describes purpose, authority, reliable inputs, options, risk, consultation, conflicts, approval, communication, implementation, records, review, and lessons for controlled professional decisions.','standard','Professional Standards',JSON_ARRAY('free resource','standard','decision making'),'PCMO Standards','published',NOW(),JSON_OBJECT('recommended',true),JSON_OBJECT('library',true,'membership',JSON_ARRAY('free','paid')),FALSE,0,'USD','Practice standard',22,59)
ON DUPLICATE KEY UPDATE title=VALUES(title),excerpt=VALUES(excerpt),body=VALUES(body),type=VALUES(type),category=VALUES(category),tags=VALUES(tags),author=VALUES(author),status='published',published_at=VALUES(published_at),flags=VALUES(flags),visibility=VALUES(visibility),sale_enabled=FALSE,price=0,currency=VALUES(currency),book_format=VALUES(book_format),page_count=VALUES(page_count),display_priority=VALUES(display_priority);
