USE pcmo;

INSERT IGNORE INTO website_pages
  (id, page_group, title, slug, menu_label, summary, body, status, sort_order)
VALUES
(UUID(),'additional','Validate a PCMO Certificate','validate_certificate','Validate Certificate','Confirm the authenticity and current status of a PCMO professional credential.','Certificate validation\n\nUse the credential identifier and recipient details shown on a PCMO certificate to request verification. Validation protects professional trust and helps employers confirm an achievement.\n\nWhat you can verify\n\nCredential title, recipient name, issue date, current status, and issuing organisation can be confirmed through the PCMO support team.','published',200),
(UUID(),'additional','Associate Project Management Certified Professional','apmc','Associate Project Management Certified Professional (APMC)','Build a strong foundation for an early career in project management.','Programme overview\n\nThe APMC pathway introduces project lifecycles, scope, scheduling, cost, quality, risk, stakeholders, communication, and professional conduct.\n\nLearning outcomes\n\nParticipants learn to support project planning, maintain project information, communicate progress, identify delivery risks, and contribute confidently within a project team.','published',210),
(UUID(),'additional','Project Management Essentials','project_management_essentials','Essentials of Project Management','Understand the essential principles used to initiate, plan, deliver, and close projects.','Programme overview\n\nThis practical introduction explains the language, tools, roles, and controls used across modern projects.\n\nProfessional application\n\nApply structured objectives, work breakdown, schedules, responsibilities, risk controls, reporting, and lessons learned to day-to-day delivery.','published',220),
(UUID(),'additional','Introduction to Project Management','introduction_project_management','Introduction to Project Management','Start with the core concepts, terminology, roles, and lifecycle of a project.','Programme overview\n\nExplore why projects are created, how success is defined, and how teams move from an idea to a controlled result.\n\nLearning pathway\n\nThe page covers initiation, planning, execution, monitoring, closure, stakeholders, governance, and continuous improvement.','published',230),
(UUID(),'additional','Project Management Fundamentals','project_management_fundamentals','Project Management Fundamentals','Develop dependable skills across scope, schedule, cost, quality, and risk.','Programme overview\n\nBuild a practical foundation for coordinating work and supporting successful delivery.\n\nCore capability\n\nTranslate objectives into deliverables, sequence activities, estimate resources, monitor performance, manage change, and communicate decisions.','published',240),
(UUID(),'additional','Agile Project Management','agile_project_management','Agile Project Management','Use adaptive planning, iterative delivery, and feedback to create value sooner.','Programme overview\n\nLearn how agile values, product backlogs, iterations, reviews, and retrospectives support uncertain and fast-moving work.\n\nProfessional application\n\nCreate transparent priorities, collaborate with stakeholders, remove blockers, inspect outcomes, and adapt delivery plans responsibly.','published',250),
(UUID(),'additional','Advanced Project Management','advanced_project_management','Advanced Project Management','Lead complex delivery environments with stronger governance and integrated controls.','Programme overview\n\nAdvance beyond foundational planning into strategic alignment, complexity, assurance, benefits, commercial awareness, and leadership.\n\nProfessional application\n\nBalance competing constraints, interpret performance evidence, govern change, recover challenged work, and lead multidisciplinary teams.','published',260),
(UUID(),'additional','Strategic Project Management','strategic_project_management','Strategic Project Management','Connect project decisions with organisational strategy, value, and long-term outcomes.','Programme overview\n\nExplore portfolio alignment, business cases, benefits, governance, investment decisions, and strategic risk.\n\nLeadership outcomes\n\nEvaluate whether projects remain valuable, align stakeholders around outcomes, and communicate evidence for executive decisions.','published',270),
(UUID(),'additional','Certified Project Manager Preparation','cpm_preparation','Certified Project Manager (CPM) Preparation','Prepare systematically for professional project management assessment.','Preparation pathway\n\nReview the project lifecycle, knowledge domains, scenario analysis, professional judgement, and assessment techniques.\n\nReadiness approach\n\nUse structured study goals, knowledge checks, practice questions, error review, and revision milestones to build confidence.','published',280),
(UUID(),'additional','Program Management','program_management','Program Management','Coordinate related projects to achieve benefits that individual projects cannot deliver alone.','Programme overview\n\nLearn program vision, governance, dependency management, benefits, stakeholder alignment, and transition into operations.\n\nLeadership outcomes\n\nCreate an integrated roadmap, manage cross-project risk, track benefits, resolve competing priorities, and sustain strategic alignment.','published',290),
(UUID(),'additional','PMO Implementation','pmo_implementation','PMO (Project Management Office) Implementation','Design and implement a PMO that improves governance, insight, and delivery capability.','Implementation pathway\n\nAssess organisational needs, choose a PMO model, define services, establish governance, select measures, and plan adoption.\n\nValue focus\n\nA successful PMO enables decisions, builds capability, simplifies controls, and demonstrates measurable value rather than adding bureaucracy.','published',300),
(UUID(),'additional','Project Management Leadership','project_management_leadership','Project Management Leadership','Lead project teams with clarity, trust, accountability, and professional judgement.','Programme overview\n\nExplore leadership styles, team development, motivation, conflict, influence, decision-making, and ethical responsibility.\n\nLeadership outcomes\n\nCreate direction, communicate purpose, build psychological safety, address performance, and guide stakeholders through change.','published',310),
(UUID(),'additional','Introduction to Contract Management','introduction_contract_management','Introduction to Contract Management','Understand the contract lifecycle and the responsibilities that protect value and relationships.','Programme overview\n\nFollow the contract from planning and formation through mobilisation, administration, performance, change, closeout, and lessons learned.\n\nProfessional application\n\nMaintain obligations, records, notices, deliverables, decisions, and communication in a disciplined and collaborative way.','published',320),
(UUID(),'additional','Contract Administration Fundamentals','contract_administration_fundamentals','Contract Administration Fundamentals','Apply reliable controls for obligations, records, changes, payments, and performance.','Programme overview\n\nDevelop the day-to-day disciplines needed to administer a contract fairly and consistently.\n\nCore capability\n\nTrack deliverables, manage correspondence, review applications, document decisions, control changes, and maintain an auditable record.','published',330),
(UUID(),'additional','Negotiation Skills for Contract Management','contract_negotiation_skills','Negotiation Skills for Contract Management','Prepare and conduct principled negotiations that protect value and working relationships.','Programme overview\n\nLearn preparation, interests, positions, options, authority, concessions, communication, and agreement documentation.\n\nProfessional application\n\nUse evidence, active listening, structured proposals, and clear approvals to reach durable and ethical outcomes.','published',340),
(UUID(),'additional','Advanced Contract Management Strategies','advanced_contract_management','Advanced Contract Management Strategies','Manage complex commercial relationships, risk, change, and performance strategically.','Programme overview\n\nExplore advanced governance, commercial strategy, performance regimes, claims avoidance, dispute management, and relationship health.\n\nLeadership outcomes\n\nIntegrate legal, commercial, operational, and stakeholder evidence to guide high-value contract decisions.','published',350),
(UUID(),'additional','Legal Aspects of Contract Management','legal_aspects_contract_management','Legal Aspects of Contract Management','Understand the legal principles that influence formation, interpretation, performance, and remedies.','Programme overview\n\nReview authority, offer, acceptance, consideration, terms, interpretation, breach, damages, termination, and dispute resolution.\n\nProfessional responsibility\n\nRecognise issues early, maintain evidence, follow delegated authority, and obtain qualified legal advice when required.','published',360),
(UUID(),'additional','Relationship Management in Contracts','relationship_management_contracts','Relationship Management in Contracts','Build collaborative commercial relationships without weakening accountability or controls.','Programme overview\n\nExplore trust, governance forums, communication protocols, performance conversations, escalation, and joint improvement.\n\nProfessional application\n\nSeparate people from problems, use shared evidence, address concerns early, and maintain a focus on mutual outcomes.','published',370),
(UUID(),'additional','Strategic Contract Management','strategic_contract_management','Strategic Contract Management','Align contract strategy, supplier performance, risk, and value with organisational priorities.','Programme overview\n\nConnect category objectives, sourcing decisions, contract design, governance, performance, innovation, and exit planning.\n\nLeadership outcomes\n\nUse portfolio insight to prioritise attention, allocate capability, protect continuity, and improve whole-life value.','published',380),
(UUID(),'additional','Ethics and Compliance in Contract Management','contract_ethics_compliance','Ethics and Compliance in Contract Management','Make transparent, fair, accountable, and compliant decisions throughout the contract lifecycle.','Programme overview\n\nExamine conflicts of interest, confidentiality, anti-bribery controls, competition, records, approvals, gifts, and reporting concerns.\n\nProfessional responsibility\n\nApply policy consistently, document judgement, challenge improper conduct, and protect public and organisational trust.','published',390),
(UUID(),'additional','International Contract Management','international_contract_management','International Contract Management','Navigate cross-border contracts, legal systems, cultures, currencies, logistics, and dispute forums.','Programme overview\n\nExplore governing law, jurisdiction, arbitration, trade terms, tax, currency, sanctions, language, and cultural expectations.\n\nProfessional application\n\nPlan for cross-border complexity early, allocate risk clearly, coordinate specialist advice, and maintain resilient international relationships.','published',400),
(UUID(),'additional','Join the Conversation','join_the_conversation','Join the Conversation','Participate in professional discussions and share practical insight with the PCMO community.','Community participation\n\nDiscover featured discussions, contribute relevant experience, ask thoughtful questions, and learn from diverse professional perspectives.\n\nCommunity standards\n\nKeep contributions respectful, evidence-informed, constructive, inclusive, and focused on professional learning.','published',410);
