import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Bell, CheckCircle2, CreditCard, Download, Eye, EyeOff, FileText, Lock, Mail, MapPin, ShieldCheck, Smartphone, User, Wallet } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";
import { api } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";

type Preferences={notification_preferences:Record<string,boolean>;privacy_settings:Record<string,string>};
type Overview={profile:{email:string;display_name:string;headline?:string;company?:string;phone?:string;location?:string;avatar_url?:string;member_number?:string;status:string;created_at:string};subscriptions:Array<{id:string;plan_name:string;price:number;currency:string;status:string;payment_method?:string;next_billing?:string;auto_renew:number}>;invoices:Array<{id:string;invoice_number:string;description?:string;amount:number;currency:string;status:string;invoice_date:string}>;purchases:Array<{id:string;title:string;amount:number;currency:string;status:string;purchased_at?:string}>;membership?:{plan_name:string;status:string;starts_at:string;ends_at?:string};recentActivity:Array<{activity_type:string;resource:string;created_at:string}>};
const clean=(v:string)=>v.trim()||null;

const PasswordInput=({label,value,set}:{label:string;value:string;set:(v:string)=>void})=>{const[show,setShow]=useState(false);return <label><Label>{label}</Label><div className="relative mt-2"><Input type={show?"text":"password"} value={value} onChange={e=>set(e.target.value)} className="pr-10"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-2.5 text-muted-foreground">{show?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></label>};
const Section=({title,description,children}:{title:string;description:string;children:React.ReactNode})=><section className="rounded-xl border bg-card p-6"><h2 className="font-heading text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p><div className="mt-6">{children}</div></section>;

const Account=()=>{
 const qc=useQueryClient(); const overview=useQuery({queryKey:["account-overview"],queryFn:()=>api<Overview>("/api/account/overview")}); const preferences=useQuery({queryKey:["preferences"],queryFn:()=>api<Preferences>("/api/preferences")});
 const[prefs,setPrefs]=useState<Preferences>({notification_preferences:{},privacy_settings:{}}); const[profile,setProfile]=useState({display_name:"",headline:"",company:"",phone:"",location:"",bio:""}); const[emailForm,setEmailForm]=useState({email:"",currentPassword:""}); const[password,setPassword]=useState({currentPassword:"",newPassword:"",confirmPassword:""}); const[message,setMessage]=useState("");
 useEffect(()=>{if(preferences.data)setPrefs(preferences.data)},[preferences.data]); useEffect(()=>{if(overview.data){const p=overview.data.profile;setProfile({display_name:p.display_name||"",headline:p.headline||"",company:p.company||"",phone:p.phone||"",location:p.location||"",bio:""});setEmailForm(x=>({...x,email:p.email}))}},[overview.data]);
 const refresh=()=>qc.invalidateQueries({queryKey:["account-overview"]});
 const saveProfile=useMutation({mutationFn:()=>{const{bio:_bio,...contact}=profile;return api("/api/profile",{method:"PUT",body:JSON.stringify({...contact,headline:clean(profile.headline),company:clean(profile.company),phone:clean(profile.phone),location:clean(profile.location)})})},onSuccess:()=>{setMessage("Contact information updated.");refresh()}});
 const savePrefs=useMutation({mutationFn:()=>api("/api/preferences",{method:"PUT",body:JSON.stringify(prefs)}),onSuccess:()=>setMessage("Preferences saved.")});
 const changeEmail=useMutation({mutationFn:()=>api("/api/account/email",{method:"PUT",body:JSON.stringify(emailForm)}),onSuccess:()=>{setEmailForm(x=>({...x,currentPassword:""}));setMessage("Login email updated.");refresh()}});
 const changePassword=useMutation({mutationFn:()=>{if(password.newPassword.length<8)throw new Error("New password must contain at least 8 characters");if(password.newPassword!==password.confirmPassword)throw new Error("Passwords do not match");return api("/api/auth/password",{method:"PUT",body:JSON.stringify({currentPassword:password.currentPassword,newPassword:password.newPassword})})},onSuccess:()=>{setPassword({currentPassword:"",newPassword:"",confirmPassword:""});setMessage("Password updated successfully.")}});
 const profileCompletion=useMemo(()=>{const p=overview.data?.profile;if(!p)return 0;return Math.round([p.display_name,p.headline,p.company,p.phone,p.location,p.avatar_url].filter(Boolean).length/6*100)},[overview.data]);
 const setNotification=(key:string,value:boolean)=>setPrefs(x=>({...x,notification_preferences:{...x.notification_preferences,[key]:value}})); const setPrivacy=(key:string,value:string)=>setPrefs(x=>({...x,privacy_settings:{...x.privacy_settings,[key]:value}}));
 const exportData=()=>{const blob=new Blob([JSON.stringify({account:overview.data,preferences:prefs},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="pcmo-account-data.json";a.click();URL.revokeObjectURL(url)};
 if(overview.isLoading)return <DashboardLayout><p>Loading account settings…</p></DashboardLayout>; if(overview.error)return <DashboardLayout><p className="text-destructive">{overview.error.message}</p></DashboardLayout>;
 const p=overview.data!.profile; const errors=[saveProfile.error,savePrefs.error,changeEmail.error,changePassword.error].find(Boolean) as Error|undefined;
 return <DashboardLayout><div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><Badge variant="secondary"><ShieldCheck className="mr-1 h-3.5 w-3.5"/>Account control center</Badge><h1 className="mt-3 font-heading text-3xl font-bold">Account Settings</h1><p className="mt-1 text-sm text-muted-foreground">Manage your identity, security, communications, privacy, billing, and account records.</p></div><Button asChild variant="outline"><Link to="/community-profile">View community profile</Link></Button></div>
 <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border bg-card p-5"><User className="h-5 w-5 text-primary"/><p className="mt-3 text-2xl font-bold">{profileCompletion}%</p><p className="text-xs text-muted-foreground">Profile completion</p></div><div className="rounded-xl border bg-card p-5"><CreditCard className="h-5 w-5 text-primary"/><p className="mt-3 text-xl font-bold">{overview.data?.membership?.plan_name||"No active plan"}</p><p className="text-xs text-muted-foreground">Membership · {overview.data?.membership?.status||"inactive"}</p></div><div className="rounded-xl border bg-card p-5"><ShieldCheck className="h-5 w-5 text-emerald-600"/><p className="mt-3 text-xl font-bold">Protected</p><p className="text-xs text-muted-foreground">Password-authenticated account</p></div></div>
 {message&&<div className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700"><CheckCircle2 className="h-4 w-4"/>{message}</div>}{errors&&<p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-destructive">{errors.message}</p>}
 <Tabs defaultValue="basic" orientation="vertical" className="grid gap-6 lg:grid-cols-[270px_1fr]"><TabsList className="h-auto flex-col items-stretch justify-start rounded-xl border bg-card p-2">{[["basic",User,"Basic + Contact"],["security",Lock,"Login + Security"],["communications",Bell,"Communication"],["privacy",Eye,"Privacy + Data"],["payments",Wallet,"Payment Methods"],["orders",FileText,"Order History"]].map(([v,I,l])=>{const Icon=I as typeof User;return <TabsTrigger key={String(v)} value={String(v)} className="justify-start gap-3 px-4 py-3"><Icon className="h-4 w-4"/>{String(l)}</TabsTrigger>})}</TabsList><div>
  <TabsContent value="basic" className="mt-0 space-y-5"><Section title="Basic & Contact Information" description="Keep your account and professional contact details accurate."><div className="grid gap-4 sm:grid-cols-2">{[["display_name","Display name"],["headline","Professional headline"],["company","Company"],["phone","Phone"],["location","Location"]].map(([k,l])=><label key={k}><Label>{l}</Label><Input className="mt-2" value={profile[k as keyof typeof profile]} onChange={e=>setProfile({...profile,[k]:e.target.value})}/></label>)}<div className="rounded-lg border bg-muted/30 p-4"><p className="text-xs text-muted-foreground">Member number</p><p className="mt-1 font-bold">{p.member_number||"Pending"}</p></div></div><Button className="mt-5" disabled={saveProfile.isPending||!profile.display_name.trim()} onClick={()=>saveProfile.mutate()}>Save contact details</Button></Section><Section title="Profile quality" description="A complete profile improves community discovery and professional credibility."><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{width:`${profileCompletion}%`}}/></div><div className="mt-4 flex gap-3"><Button asChild variant="outline"><Link to="/edit-profile">Upload profile image</Link></Button><Button asChild variant="outline"><Link to="/community-profile">Edit Resume and specialties</Link></Button></div></Section></TabsContent>
  <TabsContent value="security" className="mt-0 space-y-5"><Section title="Login email" description="Changing your login email requires your current password."><div className="grid gap-4 sm:grid-cols-2"><label><Label>Email address</Label><Input className="mt-2" type="email" value={emailForm.email} onChange={e=>setEmailForm({...emailForm,email:e.target.value})}/></label><PasswordInput label="Current password" value={emailForm.currentPassword} set={v=>setEmailForm({...emailForm,currentPassword:v})}/></div><Button className="mt-5" disabled={!emailForm.email||!emailForm.currentPassword||changeEmail.isPending} onClick={()=>changeEmail.mutate()}><Mail className="h-4 w-4"/>Update login email</Button></Section><Section title="Password" description="Use at least eight characters and avoid reusing passwords from other websites."><div className="grid gap-4"><PasswordInput label="Current password" value={password.currentPassword} set={v=>setPassword({...password,currentPassword:v})}/><div className="grid gap-4 sm:grid-cols-2"><PasswordInput label="New password" value={password.newPassword} set={v=>setPassword({...password,newPassword:v})}/><PasswordInput label="Confirm password" value={password.confirmPassword} set={v=>setPassword({...password,confirmPassword:v})}/></div></div><Button className="mt-5" disabled={changePassword.isPending||!password.currentPassword||!password.newPassword} onClick={()=>changePassword.mutate()}><Lock className="h-4 w-4"/>Change password</Button></Section><Section title="Security status" description="Important security information for your account."><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-lg border p-4"><p className="font-bold">Account status</p><Badge className="mt-2">{p.status}</Badge></div><div className="rounded-lg border p-4"><p className="font-bold">Member since</p><p className="mt-2 text-sm text-muted-foreground">{new Date(p.created_at).toLocaleDateString()}</p></div></div></Section></TabsContent>
  <TabsContent value="communications" className="mt-0"><Section title="Communication Preferences" description="Choose which operational and community messages you want to receive."><div className="space-y-3">{[["email",Mail,"Email notifications","Receive enabled notifications by email"],["whatsapp",Smartphone,"WhatsApp notifications","Receive enabled alerts through WhatsApp"],["course_reminders",Bell,"Course reminders","Progress, deadlines, and learning updates"],["event_updates",Bell,"Event updates","Registration, schedule, and venue changes"],["community_replies",Bell,"Community replies","Replies to your posts and conversations"],["volunteer",Bell,"Volunteer updates","Application and hour-verification decisions"],["marketing",Mail,"News and opportunities","Optional PCMO news and professional opportunities"]].map(([k,I,t,d])=>{const Icon=I as typeof Bell;return <label key={String(k)} className="flex items-center gap-4 rounded-lg border p-4"><Icon className="h-5 w-5 text-primary"/><span className="flex-1"><strong className="block text-sm">{String(t)}</strong><span className="text-xs text-muted-foreground">{String(d)}</span></span><Switch checked={prefs.notification_preferences[String(k)]??true} onCheckedChange={v=>setNotification(String(k),v)}/></label>})}</div><Button className="mt-5" onClick={()=>savePrefs.mutate()}>Save communication preferences</Button></Section></TabsContent>
  <TabsContent value="privacy" className="mt-0 space-y-5"><Section title="Privacy & Community Visibility" description="Control how other PCMO members discover and interact with you."><div className="grid gap-4 sm:grid-cols-2">{[["profile_visibility","Profile visibility",["public","members","private"]],["connection_requests","Connection requests",["everyone","members","nobody"]],["activity_visibility","Activity visibility",["public","connections","private"]],["volunteer_visibility","Volunteer record",["public","connections","private"]]].map(([k,l,opts])=><label key={String(k)}><Label>{String(l)}</Label><select className="mt-2 w-full rounded-md border bg-background p-2.5 text-sm" value={prefs.privacy_settings[String(k)]||String((opts as string[])[1])} onChange={e=>setPrivacy(String(k),e.target.value)}>{(opts as string[]).map(o=><option key={o} value={o}>{o[0].toUpperCase()+o.slice(1)}</option>)}</select></label>)}</div><Button className="mt-5" onClick={()=>savePrefs.mutate()}>Save privacy controls</Button></Section><Section title="Your account data" description="Download a readable copy of the account, purchase, and preference information currently available to you."><Button variant="outline" onClick={exportData}><Download className="h-4 w-4"/>Download my data</Button></Section></TabsContent>
  <TabsContent value="payments" className="mt-0 space-y-5"><Section title="Payment Methods" description="PCMO does not store complete card numbers. Payments are securely handled by Stripe."><div className="space-y-3">{overview.data!.subscriptions.map(s=><div key={s.id} className="flex items-center gap-4 rounded-lg border p-4"><div className="grid h-11 w-11 place-items-center rounded-lg bg-primary/10"><CreditCard className="h-5 w-5 text-primary"/></div><div className="flex-1"><p className="font-bold">{s.payment_method?`${s.payment_method[0].toUpperCase()+s.payment_method.slice(1)} payment`:"Payment method pending"}</p><p className="text-xs text-muted-foreground">{s.plan_name} · {s.currency} {Number(s.price||0).toFixed(2)}</p></div><Badge variant="outline">{s.status}</Badge></div>)}{!overview.data!.subscriptions.length&&<p className="rounded-lg border border-dashed p-4 text-sm text-muted-foreground">No payment method is associated with an active subscription.</p>}</div><p className="mt-5 text-xs text-muted-foreground">Payment details are created or updated during secure membership checkout.</p><Button asChild className="mt-4"><Link to="/membership">Manage membership</Link></Button></Section></TabsContent>
  <TabsContent value="orders" className="mt-0 space-y-5"><Section title="Order History" description="Invoices and paid digital-resource purchases associated with this account."><div className="space-y-3">{overview.data!.invoices.map(i=><div key={i.id} className="grid gap-2 rounded-lg border p-4 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="font-bold">{i.description||i.invoice_number}</p><p className="text-xs text-muted-foreground">{i.invoice_number} · {i.invoice_date?new Date(i.invoice_date).toLocaleDateString():"Date pending"}</p></div><p className="font-bold">{i.currency} {Number(i.amount).toFixed(2)}</p><Badge variant="outline">{i.status}</Badge></div>)}{overview.data!.purchases.map(x=><div key={x.id} className="grid gap-2 rounded-lg border p-4 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="font-bold">{x.title}</p><p className="text-xs text-muted-foreground">Digital library purchase · {x.purchased_at?new Date(x.purchased_at).toLocaleDateString():"Processing"}</p></div><p className="font-bold">{x.currency} {Number(x.amount).toFixed(2)}</p><Badge variant="outline">{x.status}</Badge></div>)}{!overview.data!.invoices.length&&!overview.data!.purchases.length&&<p className="rounded-lg border border-dashed p-4 text-sm text-muted-foreground">No orders have been recorded for this account.</p>}</div></Section></TabsContent>
 </div></Tabs></div></DashboardLayout>;
};
export default Account;
