import { ArrowRight, Award, BookOpenCheck, BriefcaseBusiness, CheckCircle2, ChevronDown, ClipboardCheck, Compass, FileText, GraduationCap, Lightbulb, Network, Search, Target, TrendingUp, UserCheck, Users } from "lucide-react";
import { Link } from "react-router-dom";
import PublicFooter from "@/components/PublicFooter";
import PublicNavigation from "@/components/PublicNavigation";

const pathways = [
  [Compass, "Early Career", "Build foundations, understand roles, gain practical exposure, document achievements, and develop professional confidence."],
  [BriefcaseBusiness, "Project Professional", "Progress through coordination, planning, controls, delivery, project management, programme, and portfolio roles."],
  [FileText, "Contract Professional", "Develop from contract support and administration into commercial, claims, negotiation, and strategic contract leadership."],
  [TrendingUp, "Specialist Path", "Deepen expertise in planning, cost, risk, quality, procurement, PMO, claims, assurance, data, or transformation."],
  [Users, "Leadership Path", "Strengthen judgement, influence, governance, team leadership, executive communication, and organisational capability."],
  [GraduationCap, "Career Transition", "Translate transferable experience, close capability gaps, build evidence, and enter project or contract-focused work."],
] as const;

const toolkit = [
  [ClipboardCheck, "Career self-assessment", "Review strengths, interests, evidence, gaps, constraints, values, and preferred professional direction."],
  [FileText, "Achievement-led CV", "Present scope, complexity, responsibility, actions, controls, outcomes, and measurable contribution."],
  [UserCheck, "Professional profile", "Build a clear headline, credible summary, capability keywords, project evidence, and certification record."],
  [Search, "Targeted job search", "Research roles and organisations, analyse requirements, prioritise fit, and track thoughtful applications."],
  [Lightbulb, "Interview preparation", "Prepare structured examples covering decisions, challenges, stakeholders, risk, contracts, and lessons."],
  [Network, "Professional networking", "Build genuine relationships through contribution, curiosity, follow-up, mentoring, and shared learning."],
] as const;

const plan = [
  ["01", "Define direction", "Choose a target role family, level, sector, location, and development timeframe."],
  ["02", "Map requirements", "Compare target-role expectations with your knowledge, experience, behaviours, and credentials."],
  ["03", "Build evidence", "Capture credible examples of responsibility, decisions, tools, complexity, and measurable outcomes."],
  ["04", "Close gaps", "Use learning, certifications, stretch assignments, volunteering, mentoring, and practical application."],
  ["05", "Position yourself", "Align your CV, profile, portfolio, conversations, and applications with the target opportunity."],
  ["06", "Review progress", "Track activity, feedback, results, learning, confidence, and changes needed in the plan."],
] as const;

const interview = [
  ["Situation", "Give only the context needed to understand scale, risk, stakeholders, and constraints."],
  ["Responsibility", "Clarify your authority, objective, accountability, and what success required."],
  ["Action", "Explain your analysis, decisions, controls, communication, and professional judgement."],
  ["Result", "State measurable outcomes, unresolved limitations, and value delivered."],
  ["Reflection", "Share what you learned and how it changed your later practice."],
] as const;

const faqs = [
  ["How do I choose between project and contract management?", "Review the work you enjoy and the problems you want to solve. Project roles often emphasise integrated delivery, coordination, controls, and outcomes; contract roles emphasise obligations, commercial performance, change, negotiation, records, and risk allocation. Many careers combine both."],
  ["What should I include in a project or contract CV?", "Include a concise profile, relevant capabilities, credentials, tools, employment history, and achievement-led examples showing scale, complexity, personal responsibility, actions, and outcomes. Protect confidential information."],
  ["How can I gain experience without holding the target job title?", "Seek stretch assignments, project work, governance support, reporting, risk reviews, procurement activity, process improvement, volunteering, simulations, mentoring, and opportunities to document transferable responsibilities."],
  ["Are certifications enough to secure a role?", "Certifications can strengthen knowledge and credibility, but employers normally consider experience, evidence, behaviours, communication, sector context, judgement, and role fit as well."],
  ["How should I prepare for competency interviews?", "Analyse the role, prepare several authentic examples, practise a structured response, quantify outcomes, explain your personal contribution, and be ready to discuss trade-offs, mistakes, ethics, and lessons."],
  ["How often should I update my career plan?", "Review it at least quarterly and after major feedback, learning, role changes, project milestones, market shifts, personal changes, or new opportunities."],
] as const;

const CareerResourcesHub = () => <div className="min-h-screen bg-white text-slate-800"><PublicNavigation active="resources"/><main>
  <section className="relative overflow-hidden bg-[#071f3b] px-6 py-24 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(220,38,38,.27),transparent_34%)]"/><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.22em] text-red-300">Build a career with direction</p><h1 className="mt-4 font-heading text-6xl font-extrabold">Career resources for project and contract professionals</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/70">Practical guidance to assess your capabilities, choose a pathway, communicate your value, find opportunities, prepare confidently, and sustain long-term professional growth.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#pathways" className="rounded bg-red-600 px-6 py-3 font-bold">Explore pathways</a><Link to="/pages/job_community" className="rounded border border-white/25 px-6 py-3 font-bold">View job community</Link></div></div><div className="rounded-3xl border border-white/15 bg-white/5 p-9 backdrop-blur"><Target className="h-14 w-14 text-red-400"/><h2 className="mt-5 text-2xl font-bold">Your career value proposition</h2><p className="mt-4 leading-7 text-white/65">The problems you can solve, the evidence you can show, the environment in which you perform, and the professional value you can create.</p><div className="mt-6 grid grid-cols-2 gap-3">{["Knowledge","Experience","Behaviours","Evidence"].map(item => <span key={item} className="rounded-lg bg-white/10 p-3 text-center text-sm font-bold">{item}</span>)}</div></div></div></section>

  <section id="pathways" className="mx-auto max-w-7xl px-6 py-20"><div className="text-center"><Compass className="mx-auto h-11 w-11 text-red-600"/><h2 className="mt-4 font-heading text-4xl font-extrabold text-[#0b3764]">Choose a career pathway</h2><p className="mx-auto mt-4 max-w-3xl leading-7 text-slate-600">Career paths are rarely perfectly linear. Use these pathways to identify a useful next direction, not to limit your options.</p></div><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{pathways.map(([Icon,title,text],index) => <article key={title} className="group relative overflow-hidden rounded-2xl border p-7 shadow-sm transition hover:-translate-y-2 hover:border-red-300 hover:shadow-xl"><span className="absolute right-5 top-3 text-6xl font-black text-slate-50">0{index+1}</span><div className="relative grid h-12 w-12 place-items-center rounded-xl bg-[#0b3764] text-white group-hover:bg-red-600"><Icon className="h-6 w-6"/></div><h3 className="relative mt-5 text-xl font-extrabold text-[#0b3764]">{title}</h3><p className="relative mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></section>

  <section className="bg-slate-50 px-6 py-20"><div className="mx-auto max-w-7xl"><p className="text-center text-sm font-bold uppercase tracking-widest text-red-600">Career toolkit</p><h2 className="mt-3 text-center font-heading text-4xl font-extrabold text-[#0b3764]">Turn ambition into professional action</h2><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{toolkit.map(([Icon,title,text]) => <article key={title} className="rounded-2xl bg-white p-7 shadow-sm"><Icon className="h-10 w-10 text-red-600"/><h3 className="mt-5 text-xl font-bold text-[#0b3764]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div><div className="mt-9 text-center"><Link to="/library" className="inline-flex items-center gap-2 rounded bg-[#0b3764] px-6 py-3 font-bold text-white">Open career templates and resources<ArrowRight className="h-4 w-4"/></Link></div></div></section>

  <section className="bg-[#0b3764] px-6 py-20 text-white"><div className="mx-auto max-w-7xl"><p className="text-center text-sm font-bold uppercase tracking-widest text-red-300">Career development plan</p><h2 className="mt-3 text-center font-heading text-4xl font-extrabold">Six steps to purposeful progress</h2><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{plan.map(([number,title,text]) => <article key={number} className="rounded-2xl border border-white/10 bg-white/5 p-7"><span className="text-4xl font-black text-red-400">{number}</span><h3 className="mt-3 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-white/65">{text}</p></article>)}</div></div></section>

  <section className="mx-auto grid max-w-7xl gap-8 px-6 py-20 lg:grid-cols-2"><article className="rounded-3xl border p-8"><Award className="h-11 w-11 text-red-600"/><h2 className="mt-5 font-heading text-3xl font-extrabold text-[#0b3764]">Build an evidence portfolio</h2><p className="mt-4 leading-8 text-slate-600">Maintain a confidential career record of responsibilities, deliverables, decisions, controls, stakeholder challenges, measurable outcomes, feedback, learning, credentials, and lessons. Remove client-sensitive information before sharing externally.</p><div className="mt-6 space-y-3">{["Project and contract summaries", "Achievement and competency examples", "Training and certification evidence", "Feedback, recognition, and lessons", "Tools, methods, and sector knowledge"].map(item => <p key={item} className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-600"/>{item}</p>)}</div></article><article className="rounded-3xl bg-red-50 p-8"><BookOpenCheck className="h-11 w-11 text-red-600"/><h2 className="mt-5 font-heading text-3xl font-extrabold text-[#0b3764]">Learning and certification</h2><p className="mt-4 leading-8 text-slate-600">Select learning that supports a defined capability gap or target responsibility. Combine structured knowledge with practice, feedback, reflection, and evidence of application.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/pages/certifications" className="rounded bg-red-600 px-5 py-3 font-bold text-white">Explore certifications</Link><Link to="/pages/learning" className="rounded border border-red-300 px-5 py-3 font-bold text-red-700">View learning</Link></div></article></section>

  <section className="bg-slate-50 px-6 py-20"><div className="mx-auto max-w-6xl"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><Lightbulb className="h-12 w-12 text-red-600"/><h2 className="mt-5 font-heading text-4xl font-extrabold text-[#0b3764]">Interview evidence framework</h2><p className="mt-5 leading-8 text-slate-600">Move beyond a basic task description. Show context, accountability, judgement, impact, and learning.</p></div><div className="space-y-4">{interview.map(([title,text],index) => <article key={title} className="flex gap-5 rounded-xl border bg-white p-5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-red-600 font-bold text-white">{index+1}</span><div><h3 className="font-bold text-[#0b3764]">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{text}</p></div></article>)}</div></div></div></section>

  <section className="mx-auto max-w-7xl px-6 py-20"><div className="grid gap-7 md:grid-cols-3">{[[Network,"Networking with purpose","Contribute useful ideas, ask thoughtful questions, follow up reliably, and build relationships before you need assistance."],[UserCheck,"Mentoring","Seek specific guidance, prepare for conversations, act on agreed steps, and share progress. Offer support to others as you develop."],[BriefcaseBusiness,"Opportunity review","Evaluate role scope, manager, culture, development, reward, location, stability, ethics, and alignment with your longer-term direction."]].map(([Icon,title,text]) => { const CardIcon=Icon as typeof Network; return <article key={String(title)} className="rounded-2xl border p-7 shadow-sm"><CardIcon className="h-10 w-10 text-red-600"/><h2 className="mt-5 text-xl font-bold text-[#0b3764]">{String(title)}</h2><p className="mt-3 leading-7 text-slate-600">{String(text)}</p></article>})}</div></section>

  <section className="bg-slate-50 px-6 py-20"><div className="mx-auto max-w-4xl"><h2 className="text-center font-heading text-4xl font-extrabold text-[#0b3764]">Career development FAQs</h2><div className="mt-10 space-y-4">{faqs.map(([question,answer]) => <details key={question} className="group rounded-xl border bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5 font-bold text-[#0b3764]">{question}<ChevronDown className="h-5 w-5 transition group-open:rotate-180"/></summary><p className="border-t px-5 py-5 leading-7 text-slate-600">{answer}</p></details>)}</div></div></section>

  <section className="bg-red-600 px-6 py-16 text-center text-white"><h2 className="font-heading text-4xl font-extrabold">Take the next career step</h2><p className="mx-auto mt-4 max-w-2xl text-white/75">Explore opportunities, strengthen your profile, connect with professionals, and build evidence for the role you want next.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link to="/pages/job_community" className="rounded bg-white px-6 py-3 font-bold text-red-600">Explore jobs</Link><Link to="/pages/membership_community" className="rounded border border-white/40 px-6 py-3 font-bold">Join the community</Link></div></section>
</main><PublicFooter/></div>;

export default CareerResourcesHub;
