import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Award, Briefcase, Camera, Check, Clock, ExternalLink, FileText, Heart, Link2, MapPin, MessageSquare, Plus, Search, UserPlus, Users } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";
import RichCommentEditor, { RichTextPreview } from "@/components/RichCommentEditor";
import { api, resourceApi } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";

type Profile={id:string;display_name:string;headline?:string;bio?:string;company?:string;location?:string;avatar_url?:string;cover_url?:string;member_number?:string;specialties?:string[];open_to?:string[];links?:Record<string,string>;resume_text?:string;resume_file_url?:string};
type Project={id:string;title:string;role_title?:string;organisation?:string;description?:string;skills?:string[];project_url?:string;started_on?:string;ended_on?:string;status:string};
type Person={id:string;display_name:string;headline?:string;company?:string;location?:string;avatar_url?:string};
type Connection=Person&{id:string;member_id?:string;status:string;created_at:string};
type Post={id:string;title:string;content:string;category?:string;likes:number;created_at:string};
type Comment={id:string;content:string;author_name?:string;created_at:string};
type ProfileData={profile:Profile;projects:Project[];badges:Array<{id:string;name:string;description?:string;icon?:string;color?:string;issued_by:string;issued_at?:string}>;recommendations:Array<{id:string;author_name:string;author_headline?:string;content:string;relationship?:string}>;connections:Connection[];invites:Connection[];contributions:Post[];volunteering:Array<{id:string;opportunity_title:string;category?:string;status:string;hours_logged:number}>};

const Avatar=({person,size="md"}:{person:Partial<Person>;size?:"md"|"lg"})=><div className={`${size==="lg"?"h-28 w-28 text-2xl":"h-12 w-12 text-sm"} grid shrink-0 place-items-center overflow-hidden rounded-full border-4 border-background bg-primary font-bold text-primary-foreground`}>{person.avatar_url?<img src={person.avatar_url} alt="" className="h-full w-full object-cover"/>:(person.display_name||"M").split(/\s+/).map(x=>x[0]).join("").slice(0,2)}</div>;
const date=(v?:string)=>v?new Date(v).toLocaleDateString(undefined,{month:"short",year:"numeric"}):"Present";

const CommunityProfile=()=>{
 const qc=useQueryClient(); const [tab,setTab]=useState("overview"); const [edit,setEdit]=useState(false); const [projectOpen,setProjectOpen]=useState(false); const [postOpen,setPostOpen]=useState(false); const [activePost,setActivePost]=useState<Post|null>(null); const [comment,setComment]=useState(""); const [peopleSearch,setPeopleSearch]=useState("");
 const profile=useQuery({queryKey:["community-profile-full"],queryFn:()=>api<ProfileData>("/api/community/profile")});
 const people=useQuery({queryKey:["community-people",peopleSearch],queryFn:()=>api<Person[]>(`/api/community/people?search=${encodeURIComponent(peopleSearch)}`),enabled:tab==="connections"});
 const [profileForm,setProfileForm]=useState({display_name:"",headline:"",bio:"",company:"",location:"",cover_url:"",specialties:"",open_to:"",linkedin:"",website:"",resume_text:"",resume_file_url:""});
 const [cvFile,setCvFile]=useState<File | null>(null);
 const [cvSections,setCvSections]=useState<Record<string,string> | null>(null);
 const [cvUploadError,setCvUploadError]=useState<string | null>(null);
 const [projectForm,setProjectForm]=useState({title:"",role_title:"",organisation:"",description:"",skills:"",project_url:"",started_on:"",ended_on:"",status:"published"});
 const [postForm,setPostForm]=useState({title:"",content:"",category:"General"});
 const comments=useQuery({queryKey:["post-comments",activePost?.id],queryFn:()=>resourceApi.list<Comment>("post-comments",{post_id:activePost!.id,limit:100}),enabled:Boolean(activePost)});
 const refresh=()=>qc.invalidateQueries({queryKey:["community-profile-full"]});
 const openEdit=()=>{const p=profile.data!.profile;setProfileForm({display_name:p.display_name||"",headline:p.headline||"",bio:p.bio||"",company:p.company||"",location:p.location||"",cover_url:p.cover_url||"",specialties:(p.specialties||[]).join(", "),open_to:(p.open_to||[]).join(", "),linkedin:p.links?.linkedin||"",website:p.links?.website||"",resume_text:p.resume_text||"",resume_file_url:p.resume_file_url||""});setCvSections(null);setCvUploadError(null);setCvFile(null);setEdit(true)};
 const saveProfile=useMutation({mutationFn:()=>api("/api/profile",{method:"PUT",body:JSON.stringify({...profileForm,specialties:profileForm.specialties.split(",").map(x=>x.trim()).filter(Boolean),open_to:profileForm.open_to.split(",").map(x=>x.trim()).filter(Boolean),links:{linkedin:profileForm.linkedin,website:profileForm.website}})}),onSuccess:()=>{setEdit(false);refresh()}});
 const standardizeCv=useMutation({
   mutationFn: async (file: File) => {
     const formData = new FormData();
     formData.append("file", file);
     const response = await fetch(`${import.meta.env.VITE_API_URL ?? ""}/api/profile/cv/standardize`, {
       method: "POST",
       headers: { ...(localStorage.getItem("pcmo_token") ? { Authorization: `Bearer ${localStorage.getItem("pcmo_token")}` } : {}) },
       body: formData,
     });
     if (!response.ok) {
       const payload = await response.json().catch(() => null);
       throw new Error(payload?.error || "Failed to standardize the CV.");
     }
     return response.json() as Promise<{
       standardized_text: string;
       sections: Record<string,string>;
       original_file_url: string;
       original_file_name: string;
     }>;
   },
   onSuccess: (data) => {
     setProfileForm((current) => ({ ...current, resume_text: data.standardized_text, resume_file_url: data.original_file_url }));
     setCvSections(data.sections);
     setCvUploadError(null);
     setCvFile(null);
   },
   onError: (error) => {
     setCvUploadError(error instanceof Error ? error.message : "CV upload failed.");
   },
 });
 const addProject=useMutation({mutationFn:()=>resourceApi.create("member-projects",{...projectForm,skills:projectForm.skills.split(",").map(x=>x.trim()).filter(Boolean)}),onSuccess:()=>{setProjectOpen(false);setProjectForm({title:"",role_title:"",organisation:"",description:"",skills:"",project_url:"",started_on:"",ended_on:"",status:"published"});refresh()}});
 const createPost=useMutation({mutationFn:()=>resourceApi.create("community-posts",{...postForm,status:"published",likes:0,views:0}),onSuccess:()=>{setPostOpen(false);setPostForm({title:"",content:"",category:"General"});refresh()}});
 const addComment=useMutation({mutationFn:()=>resourceApi.create("post-comments",{post_id:activePost!.id,content:comment,likes:0}),onSuccess:()=>{setComment("");qc.invalidateQueries({queryKey:["post-comments",activePost?.id]})}});
 const connect=useMutation({mutationFn:(id:string)=>api(`/api/community/connections/${id}`,{method:"POST",body:"{}"}),onSuccess:()=>qc.invalidateQueries({queryKey:["community-people"]})});
 const respond=useMutation({mutationFn:({id,status}:{id:string;status:"accepted"|"declined"})=>api(`/api/community/connections/${id}`,{method:"PUT",body:JSON.stringify({status})}),onSuccess:refresh});
 const p=profile.data?.profile;
 const connectedIds=useMemo(
   () => new Set(profile.data?.connections?.map((x) => x.member_id) ?? []),
   [profile.data?.connections],
 );
 if(profile.isLoading)return <DashboardLayout><p>Loading your professional community profile…</p></DashboardLayout>;
 if(profile.error||!p)return <DashboardLayout><p className="text-destructive">{profile.error?.message||"Profile unavailable"}</p></DashboardLayout>;
 const counts={connections:profile.data?.connections.length ?? 0,projects:profile.data?.projects.length ?? 0,contributions:profile.data?.contributions.length ?? 0,volunteering:profile.data?.volunteering.length ?? 0};
 const pendingInvites=profile.data.invites.length;
 return <DashboardLayout><div className="mx-auto max-w-7xl space-y-6">
  <section className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="relative h-52 bg-gradient-to-br from-[#061d39] via-[#17477a] to-red-600" style={p.cover_url?{backgroundImage:`linear-gradient(90deg,rgba(4,25,50,.45),rgba(171,22,36,.2)),url(${p.cover_url})`,backgroundSize:"cover",backgroundPosition:"center"}:undefined}><Button className="absolute right-5 top-5" variant="secondary" onClick={openEdit}><Camera className="h-4 w-4"/>Edit profile</Button></div><div className="relative px-6 pb-7 md:px-10"><div className="flex flex-col gap-5 md:flex-row md:items-center"><div className="-mt-14 shrink-0"><Avatar person={p} size="lg"/></div><div className="min-w-0 flex-1 pt-1 md:pt-5"><h1 className="break-words font-heading text-3xl font-bold leading-tight">{p.display_name}</h1><p className="mt-1 text-muted-foreground">{p.headline||"PCMO Community Member"}</p><div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-muted-foreground">{p.company&&<span className="flex items-center gap-1"><Briefcase className="h-3.5 w-3.5"/>{p.company}</span>}{p.location&&<span className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5"/>{p.location}</span>}<span>{p.member_number||"PCMO member"}</span></div></div><Button className="mt-1 shrink-0 self-start md:mt-5 md:self-center" variant="outline" onClick={()=>setTab("connections")}><UserPlus className="h-4 w-4"/>Grow your network</Button></div></div></section>
  <Tabs value={tab} onValueChange={setTab}><TabsList className="h-auto w-full justify-start overflow-x-auto rounded-xl border bg-card p-1"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="connections">Connections ({counts.connections}){pendingInvites ? <span className="ml-2 inline-flex items-center rounded-full bg-primary px-2 py-0.5 text-[10px] font-semibold uppercase text-white">{pendingInvites} pending</span> : null}</TabsTrigger><TabsTrigger value="projects">Projects ({counts.projects})</TabsTrigger><TabsTrigger value="contributions">Contributions ({counts.contributions})</TabsTrigger><TabsTrigger value="volunteering">Volunteering ({counts.volunteering})</TabsTrigger></TabsList>
   <TabsContent value="overview" className="space-y-5"><section className="grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><div className="rounded-xl border bg-card p-6"><div className="flex justify-between"><h2 className="font-heading text-xl font-bold">About me</h2><Button size="sm" variant="ghost" onClick={openEdit}>Edit</Button></div><p className="mt-4 whitespace-pre-wrap leading-7 text-muted-foreground">{p.bio||"Add your professional story, experience, and goals."}</p><h3 className="mt-6 text-sm font-bold">Specialties</h3><div className="mt-3 flex flex-wrap gap-2">{(p.specialties||[]).map(x=><Badge key={x} variant="outline">{x}</Badge>)}</div></div><div className="rounded-xl border bg-card p-6"><h2 className="font-heading text-xl font-bold">Professional details</h2><h3 className="mt-5 text-sm font-bold">Open to</h3><p className="mt-2 text-sm text-muted-foreground">{(p.open_to||[]).join(" · ")||"Add mentoring, speaking, collaboration, or consulting interests."}</p><h3 className="mt-5 text-sm font-bold">Links</h3>{Object.entries(p.links||{}).filter(([,v])=>v).map(([k,v])=><a key={k} href={v} target="_blank" rel="noreferrer" className="mt-2 flex items-center gap-2 text-sm font-medium text-primary"><ExternalLink className="h-4 w-4"/>{k}</a>)}</div></section><section className="rounded-xl border bg-card p-6"><h2 className="font-heading text-xl font-bold">Badges</h2><div className="mt-5 flex flex-wrap gap-5">{profile.data.badges.map(b=><div key={b.id} className="w-28 text-center"><div style={{background:b.color||"#143b73"}} className="mx-auto grid h-16 w-16 place-items-center rounded-full border-4 border-white text-white shadow"><Award className="h-8 w-8"/></div><p className="mt-2 text-xs font-bold">{b.name}</p></div>)}{!profile.data.badges.length&&<p className="text-sm text-muted-foreground">Badges issued by PCMO will appear here.</p>}</div></section><section className="rounded-xl border bg-card p-6"><div className="flex justify-between"><h2 className="font-heading text-xl font-bold">Resume</h2><Button size="sm" variant="ghost" onClick={openEdit}>Edit</Button></div><p className="mt-4 whitespace-pre-wrap leading-7 text-muted-foreground">{p.resume_text||"Add a concise Resume to showcase your professional journey."}</p></section><section className="rounded-xl border bg-card p-6"><h2 className="font-heading text-xl font-bold">Recommendations</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{profile.data.recommendations.map(r=><blockquote key={r.id} className="rounded-lg border p-4"><p className="text-sm leading-6">“{r.content}”</p><p className="mt-3 text-sm font-bold">{r.author_name}</p><p className="text-xs text-muted-foreground">{r.author_headline||r.relationship}</p></blockquote>)}{!profile.data.recommendations.length&&<p className="text-sm text-muted-foreground">No published recommendations yet.</p>}</div></section></TabsContent>
   <TabsContent value="connections" className="space-y-5"><section className="rounded-xl border bg-card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-heading text-xl font-bold">Invitations</h2>{pendingInvites ? <span className="inline-flex items-center rounded-full bg-primary px-3 py-1 text-xs font-semibold uppercase text-white">{pendingInvites} pending</span> : null}</div><div className="mt-4 space-y-3">{profile.data.invites.map(i=><div key={i.id} className="flex items-center gap-4 rounded-lg border p-4"><Avatar person={i}/><div className="flex-1"><p className="font-bold">{i.display_name}</p><p className="text-sm text-muted-foreground">{i.headline||i.company} · {i.location}</p></div><Button variant="ghost" onClick={()=>respond.mutate({id:i.id,status:"declined"})}>Decline</Button><Button onClick={()=>respond.mutate({id:i.id,status:"accepted"})}>Accept</Button></div>)}{!profile.data.invites.length&&<p className="text-sm text-muted-foreground">No pending invitations.</p>}</div></section><section className="rounded-xl border bg-card p-6"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Find members by name, role, company, or location" value={peopleSearch} onChange={e=>setPeopleSearch(e.target.value)}/></div><div className="mt-5 grid gap-3 md:grid-cols-2">{people.data?.map(person=><div key={person.id} className="flex items-center gap-3 rounded-lg border p-4"><Avatar person={person}/><div className="min-w-0 flex-1"><p className="font-bold">{person.display_name}</p><p className="truncate text-xs text-muted-foreground">{person.headline||person.company} · {person.location}</p></div><Button size="sm" variant="outline" disabled={connectedIds.has(person.id)||connect.isPending} onClick={()=>connect.mutate(person.id)}>{connectedIds.has(person.id)?<Check className="h-4 w-4"/>:<UserPlus className="h-4 w-4"/>}</Button></div>)}</div></section></TabsContent>
   <TabsContent value="projects"><div className="mb-4 flex justify-end"><Button onClick={()=>setProjectOpen(true)}><Plus className="h-4 w-4"/>Add project</Button></div><div className="grid gap-4 md:grid-cols-2">{profile.data.projects.map(x=><article key={x.id} className="rounded-xl border bg-card p-6"><Badge variant="outline">{x.status}</Badge><h2 className="mt-3 text-xl font-bold">{x.title}</h2><p className="mt-1 text-sm text-muted-foreground">{x.role_title} · {x.organisation}</p><p className="mt-4 text-sm leading-6">{x.description}</p><p className="mt-4 text-xs text-muted-foreground">{date(x.started_on)} — {date(x.ended_on)}</p><div className="mt-3 flex flex-wrap gap-2">{x.skills?.map(s=><Badge key={s} variant="secondary">{s}</Badge>)}</div></article>)}</div></TabsContent>
   <TabsContent value="contributions"><div className="mb-4 flex justify-end"><Button onClick={()=>setPostOpen(true)}><Plus className="h-4 w-4"/>New contribution</Button></div><div className="space-y-4">{profile.data.contributions.map(x=><article key={x.id} className="rounded-xl border bg-card p-6"><div className="flex justify-between"><Badge>{x.category||"General"}</Badge><span className="text-xs text-muted-foreground">{date(x.created_at)}</span></div><h2 className="mt-4 text-xl font-bold">{x.title}</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{x.content}</p><Button className="mt-4" variant="ghost" onClick={()=>setActivePost(x)}><MessageSquare className="h-4 w-4"/>Replies</Button></article>)}</div></TabsContent>
   <TabsContent value="volunteering"><div className="grid gap-4 md:grid-cols-2">{profile.data.volunteering.map(v=><article key={v.id} className="rounded-xl border bg-card p-6"><div className="flex justify-between"><Award className="h-6 w-6 text-primary"/><Badge>{v.status}</Badge></div><h2 className="mt-4 text-xl font-bold">{v.opportunity_title}</h2><p className="mt-1 text-sm text-muted-foreground">{v.category}</p><p className="mt-5 text-2xl font-bold">{Number(v.hours_logged)}h</p><p className="text-xs text-muted-foreground">Verified volunteer hours</p></article>)}</div></TabsContent>
  </Tabs>
 </div>
 <Dialog open={edit} onOpenChange={setEdit}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>Edit professional profile</DialogTitle></DialogHeader><div className="grid gap-4 sm:grid-cols-2">{[["display_name","Display name"],["headline","Headline"],["company","Company"],["location","Location"],["cover_url","Cover image URL"],["specialties","Specialties (comma separated)"],["open_to","Open to (comma separated)"],["linkedin","LinkedIn URL"],["website","Website URL"]].map(([k,l])=><label key={k}><Label>{l}</Label><Input className="mt-2" value={String(profileForm[k as keyof typeof profileForm])} onChange={e=>setProfileForm({...profileForm,[k]:e.target.value})}/></label>)}<label className="sm:col-span-2"><Label>About me</Label><Textarea className="mt-2" rows={6} value={profileForm.bio} onChange={e=>setProfileForm({...profileForm,bio:e.target.value})}/></label><label className="sm:col-span-2"><Label>Upload CV</Label><div className="mt-2 flex flex-col gap-3"><label className="inline-flex cursor-pointer items-center gap-2 rounded-md border border-dashed border-border px-3 py-2 text-sm transition hover:bg-muted/50"><input type="file" accept=".pdf,.docx,.txt" className="hidden" onChange={(event)=>{const file=event.target.files?.[0];setCvFile(file||null);if(file){setCvUploadError(null);}}}/><FileText className="h-4 w-4"/><span>{cvFile?.name||"Choose a PDF, DOCX, or TXT file"}</span></label><div className="flex flex-wrap gap-3"><Button variant="outline" disabled={!cvFile || standardizeCv.isLoading} onClick={()=>{if(cvFile) standardizeCv.mutate(cvFile);}}>Parse & standardize</Button>{profileForm.resume_text && <Button variant="secondary" onClick={() => {const blob=new Blob([profileForm.resume_text],{type:"text/markdown"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="standardized-cv.md";document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);}}>Download standardized CV</Button>}</div>{cvUploadError && <p className="text-sm text-destructive">{cvUploadError}</p>}</div></label><label className="sm:col-span-2"><Label>Standardized Resume text</Label><Textarea className="mt-2" rows={8} value={profileForm.resume_text} onChange={e=>setProfileForm({...profileForm,resume_text:e.target.value})}/></label>{cvSections && <div className="sm:col-span-2 rounded-xl border bg-muted/30 p-4"><h3 className="font-semibold">Detected sections</h3><div className="mt-3 space-y-3">{Object.entries(cvSections).map(([section, content]) => content ? <div key={section}><p className="text-sm font-semibold uppercase tracking-[0.08em] text-muted-foreground">{section.replace(/_/g, " ")}</p><p className="whitespace-pre-wrap text-sm text-slate-800">{content}</p></div> : null)}</div></div>} </div><DialogFooter><Button onClick={()=>saveProfile.mutate()}>Save profile</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={projectOpen} onOpenChange={setProjectOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Add project</DialogTitle></DialogHeader><div className="grid gap-4 sm:grid-cols-2">{[["title","Project title"],["role_title","Your role"],["organisation","Organisation"],["skills","Skills (comma separated)"],["project_url","Project URL"],["started_on","Start date"],["ended_on","End date"]].map(([k,l])=><label key={k}><Label>{l}</Label><Input className="mt-2" type={k.endsWith("_on")?"date":"text"} value={String(projectForm[k as keyof typeof projectForm])} onChange={e=>setProjectForm({...projectForm,[k]:e.target.value})}/></label>)}<label className="sm:col-span-2"><Label>Description</Label><Textarea className="mt-2" rows={5} value={projectForm.description} onChange={e=>setProjectForm({...projectForm,description:e.target.value})}/></label></div><DialogFooter><Button disabled={!projectForm.title} onClick={()=>addProject.mutate()}>Publish project</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={postOpen} onOpenChange={setPostOpen}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Share a contribution</DialogTitle></DialogHeader><Input placeholder="Contribution title" value={postForm.title} onChange={e=>setPostForm({...postForm,title:e.target.value})}/><RichCommentEditor value={postForm.content} onChange={content=>setPostForm({...postForm,content})}/><DialogFooter><Button disabled={!postForm.title||!postForm.content} onClick={()=>createPost.mutate()}>Publish</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={Boolean(activePost)} onOpenChange={o=>!o&&setActivePost(null)}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{activePost?.title}</DialogTitle></DialogHeader><div className="space-y-3">{comments.data?.rows.map(c=><div key={c.id} className="rounded-lg border p-4"><p className="font-bold">{c.author_name||"PCMO Member"}</p><RichTextPreview value={c.content}/></div>)}</div><RichCommentEditor value={comment} onChange={setComment} minHeight="150px"/><DialogFooter><Button disabled={!comment.trim()} onClick={()=>addComment.mutate()}>Post reply</Button></DialogFooter></DialogContent></Dialog>
 </DashboardLayout>;
};
export default CommunityProfile;
