import { ArrowRight, Award, BriefcaseBusiness, CalendarCheck, CalendarDays, CheckCircle2, ChevronDown, Clock3, Globe2, MapPin, MessageCircle, Network, Presentation, ShieldCheck, Sparkles, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import PublicFooter from "@/components/PublicFooter";
import PublicNavigation from "@/components/PublicNavigation";
import { api } from "@/lib/api";

const formats = [
  [Presentation,"Conferences and summits","Multi-session programmes connecting strategic questions, technical practice, leadership, research, and professional networking."],
  [MessageCircle,"Roundtables","Moderated small-group discussions where experienced professionals compare context, evidence, decisions, and lessons."],
  [BriefcaseBusiness,"Masterclasses","Focused expert-led sessions that develop practical capability through examples, controls, exercises, and application."],
  [Network,"Networking forums","Structured introductions and themed conversations designed to create useful professional relationships and collaboration."],
  [Award,"Certification events","Pathway briefings, preparation clinics, assessor guidance, recognition events, and continuing development sessions."],
  [Globe2,"Hybrid and virtual events","Accessible participation across locations through clear joining information, appropriate technology, and online engagement."],
] as const;

type PublicEvent = { id:string; title:string; description?:string; event_type:string; category?:string; event_date:string; event_time?:string; location?:string; capacity:number; status:string; attendees:number };

const programme: PublicEvent[] = [
  {id:"8f600000-0000-4000-8000-000000000001",title:"Integrated Project and Contract Controls Forum",description:"A practical interactive forum connecting scope, schedule, cost, risk, change, obligations, notices, records, and forecasts into one decision-useful control environment.",event_type:"Forum",category:"Project Controls",event_date:"2026-08-28",event_time:"14:00:00",location:"Virtual event",capacity:150,status:"scheduled",attendees:0},
  {id:"8f600000-0000-4000-8000-000000000002",title:"PCMO Future Practice Summit",description:"A hybrid summit exploring responsible AI, integrated project and contract information, sustainability, new delivery models, professional accountability, and future capability.",event_type:"Summit",category:"Digital Practice",event_date:"2026-09-17",event_time:"09:00:00",location:"Dubai + Online",capacity:250,status:"scheduled",attendees:0},
  {id:"8f600000-0000-4000-8000-000000000003",title:"Contract Administration in Practice Roundtable",description:"A moderated discussion on notices, records, payment, change, relationships, escalation, claims avoidance, commercial judgement, and disciplined contract closeout.",event_type:"Roundtable",category:"Contract Management",event_date:"2026-10-08",event_time:"15:00:00",location:"Virtual event",capacity:80,status:"scheduled",attendees:0},
  {id:"8f600000-0000-4000-8000-000000000004",title:"Project Leadership and Governance Forum",description:"An advanced forum covering sponsorship, authority, decision rights, tolerances, assurance, benefits ownership, ethical challenge, and leadership through uncertainty.",event_type:"Forum",category:"Governance",event_date:"2026-11-12",event_time:"10:00:00",location:"Abu Dhabi + Online",capacity:180,status:"scheduled",attendees:0},
  {id:"8f600000-0000-4000-8000-000000000005",title:"Early Career Project and Contract Management Networking Lab",description:"A structured networking and capability session for students and early-career professionals to practise introductions, discuss career pathways, meet peers, and identify development priorities.",event_type:"Networking",category:"Professional Growth",event_date:"2026-12-03",event_time:"16:00:00",location:"Virtual event",capacity:120,status:"scheduled",attendees:0},
  {id:"8f600000-0000-4000-8000-000000000006",title:"Certification Pathways and Assessment Clinic",description:"A practical clinic explaining PCMO certification pathways, eligibility, preparation, evidence, assessment expectations, professional conduct, results, and continuing development.",event_type:"Clinic",category:"Certification",event_date:"2027-01-21",event_time:"14:00:00",location:"Virtual event",capacity:160,status:"scheduled",attendees:0},
];

const journey = [
  ["01","Discover","Review the purpose, audience, format, outcomes, speakers, date, time zone, location, access conditions, and prerequisites."],
  ["02","Register","Sign in to your member panel, select the event, confirm registration, and check that your account and contact details are current."],
  ["03","Prepare","Read available briefing material, define your learning objective, prepare relevant questions, and test joining technology for online events."],
  ["04","Participate","Arrive on time, contribute respectfully, protect confidential information, capture useful insights, and connect with relevant participants."],
  ["05","Apply","Translate the strongest learning into a workplace discussion, control improvement, professional objective, or carefully scoped action."],
  ["06","Record","Document participation, learning, reflection, evidence, and application in your professional development record where appropriate."],
] as const;

const standards = [
  ["Purpose and relevance","Every event should address a meaningful professional need with a clearly defined audience and useful outcomes."],
  ["Credible contribution","Speakers and facilitators are selected for relevant knowledge, experience, responsibility, research, or professional contribution."],
  ["Inclusive participation","Events should support respectful access, clear communication, varied perspectives, and appropriate opportunities to contribute."],
  ["Safe professional conduct","Harassment, discrimination, intimidation, undisclosed promotion, and misuse of personal or confidential information are not acceptable."],
  ["Transparent interests","Material sponsorship, commercial relationships, conflicts, evidence limitations, and speaker perspectives should be clear."],
  ["Responsible application","Event content supports professional learning and does not replace governing law, contracts, standards, authority, or specialist advice."],
] as const;

const faqs = [
  ["How do I register for an event?","Sign in, open My Events, and select Register on an available event. The page updates immediately to show your registration status."],
  ["Can I cancel my registration?","Yes. Open My Events and choose Cancel registration before the event. Early cancellation releases capacity for another member."],
  ["Where do I find joining or venue information?","The event record shows its date, time, location, and status. Online joining information is released to eligible registered participants when available."],
  ["Are any events available to free members?","Selected online forums, webinars, briefings, and community sessions may be available to free members. Other events may require an eligible membership, invitation, enrolment, or fee."],
  ["What happens when an event reaches capacity?","Registration may close when the stated capacity is reached. PCMO may operate a waitlist or publish another session where demand and programme arrangements permit."],
  ["Will sessions be recorded?","Recording varies by event, speaker permission, confidentiality, participation format, and production requirements. Available recordings may appear in Webinars or the Library."],
  ["Can event participation count as professional development?","Relevant participation may support a development record when you document learning, reflection, and application. Recognition remains subject to the rules of the relevant certification or professional body."],
  ["How can I speak, sponsor, host, or partner with PCMO?","Contact PCMO with the proposed contribution, audience value, credentials, format, resources, commercial interests, conflicts, and any venue, technology, or timing requirements."],
  ["What conduct is expected?","Participate respectfully, follow moderator and venue instructions, protect confidential and personal information, avoid harassment, and disclose relevant commercial interests."],
  ["What if an event changes or is cancelled?","PCMO will update the event status and available details. Registered participants should monitor their dashboard and notifications before travel or joining."],
] as const;

const EventsHub = () => {
  const events = useQuery({ queryKey:["public-events"], queryFn:()=>api<PublicEvent[]>("/api/public/events") });
  const currentProgramme = events.data?.length ? events.data : programme;
  return <div className="min-h-screen bg-white text-slate-800"><PublicNavigation active="resources"/><main>
  <section className="relative overflow-hidden bg-[#071f3b] px-6 py-24 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(220,38,38,.3),transparent_35%)]"/><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.22em] text-red-300">PCMO Events</p><h1 className="mt-4 font-heading text-5xl font-extrabold leading-tight md:text-6xl">Learn together. Connect with purpose. Lead better.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/70">Conferences, forums, roundtables, masterclasses, certification events, and professional networking for the project and contract management community.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/events" className="inline-flex items-center gap-2 rounded bg-red-600 px-6 py-3 font-bold"><CalendarCheck className="h-4 w-4"/>View and register</Link><a href="#programme" className="rounded border border-white/25 px-6 py-3 font-bold">Explore programme</a></div></div><div className="grid grid-cols-2 gap-4">{[[CalendarDays,"Live programme"],[Globe2,"Global access"],[Users,"Professional community"],[Sparkles,"Practical insight"]].map(([Icon,label]) => { const CardIcon=Icon as typeof CalendarDays; return <div key={String(label)} className="rounded-2xl border border-white/10 bg-white/5 p-7 text-center backdrop-blur"><CardIcon className="mx-auto h-10 w-10 text-red-400"/><p className="mt-4 font-bold">{String(label)}</p></div>})}</div></div></section>
  <section className="mx-auto max-w-7xl px-6 py-20"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-red-600">Ways to participate</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">An event format for every objective</h2></div><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{formats.map(([Icon,title,text]) => <article key={title} className="group rounded-2xl border p-7 shadow-sm transition hover:-translate-y-1 hover:border-red-300 hover:shadow-xl"><div className="grid h-12 w-12 place-items-center rounded-xl bg-[#0b3764] text-white group-hover:bg-red-600"><Icon className="h-6 w-6"/></div><h3 className="mt-5 text-xl font-extrabold text-[#0b3764]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></section>
  <section id="programme" className="bg-slate-50 px-6 py-20"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-red-600">Live programme</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">Upcoming professional conversations</h2></div><Link to="/events" className="inline-flex items-center gap-2 font-bold text-red-600">Registration and availability<ArrowRight className="h-4 w-4"/></Link></div><div className="mt-10 grid gap-5 lg:grid-cols-2">{currentProgramme.map(event => <article key={event.id} className="rounded-2xl border bg-white p-7 shadow-sm"><div className="flex flex-wrap gap-2 text-xs font-bold uppercase tracking-wider text-red-600"><span>{new Date(`${event.event_date}T00:00:00`).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"})}</span><span className="text-slate-300">•</span><span>{event.event_time?.slice(0,5) || "TBA"}</span><span className="text-slate-300">•</span><span>{event.location || "Online"}</span><span className="text-slate-300">•</span><span>{event.category}</span></div><h3 className="mt-3 text-xl font-extrabold text-[#0b3764]">{event.title}</h3><p className="mt-3 leading-7 text-slate-600">{event.description}</p><div className="mt-5 flex items-center justify-between border-t pt-4 text-xs text-slate-500"><span>{event.event_type} · {event.status}</span><span>{event.attendees} / {event.capacity} registered</span></div></article>)}</div><p className="mt-6 text-sm text-slate-500">This programme uses the same event records as the Student Portal. Sign in to register, cancel, and view complete event details.</p></div></section>
  <section className="bg-[#0b3764] px-6 py-20 text-white"><div className="mx-auto max-w-7xl"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-red-300">Participation journey</p><h2 className="mt-3 font-heading text-4xl font-extrabold">From discovery to professional application</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{journey.map(([number,title,text]) => <article key={number} className="rounded-2xl border border-white/10 bg-white/5 p-7"><span className="text-4xl font-black text-red-400">{number}</span><h3 className="mt-3 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-white/65">{text}</p></article>)}</div></div></section>
  <section className="bg-red-50 px-6 py-20"><div className="mx-auto max-w-7xl"><div className="text-center"><ShieldCheck className="mx-auto h-12 w-12 text-red-600"/><h2 className="mt-4 font-heading text-4xl font-extrabold text-[#0b3764]">Event quality and conduct standards</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{standards.map(([title,text]) => <article key={title} className="rounded-2xl bg-white p-6 shadow-sm"><CheckCircle2 className="h-7 w-7 text-emerald-600"/><h3 className="mt-4 text-lg font-bold text-[#0b3764]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-4xl px-6 py-20"><h2 className="text-center font-heading text-4xl font-extrabold text-[#0b3764]">Events FAQs</h2><div className="mt-10 space-y-4">{faqs.map(([question,answer]) => <details key={question} className="group rounded-xl border bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5 font-bold text-[#0b3764]">{question}<ChevronDown className="h-5 w-5 shrink-0 transition group-open:rotate-180"/></summary><p className="border-t px-5 py-5 leading-7 text-slate-600">{answer}</p></details>)}</div></section>
  <section className="bg-red-600 px-6 py-16 text-center text-white"><CalendarCheck className="mx-auto h-11 w-11"/><h2 className="mt-4 font-heading text-4xl font-extrabold">Find your next PCMO event</h2><p className="mx-auto mt-4 max-w-2xl text-white/80">Sign in to see live availability, register or cancel, and keep your professional programme organised.</p><Link to="/events" className="mt-7 inline-flex rounded bg-white px-6 py-3 font-bold text-red-600">Open My Events</Link></section>
</main><PublicFooter/></div>;
};
export default EventsHub;
