import { ArrowRight, Award, BookOpen, BriefcaseBusiness, CheckCircle2, ChevronDown, ClipboardCheck, FileText, GraduationCap, HandHeart, HeartHandshake, Lightbulb, MessageCircle, Mic2, Network, Scale, Search, ShieldCheck, Sparkles, Target, Users } from "lucide-react";
import { Link } from "react-router-dom";
import PublicFooter from "@/components/PublicFooter";
import PublicNavigation from "@/components/PublicNavigation";

const opportunities = [
  [HandHeart,"Volunteer with PCMO","Support programmes, events, community activities, learning initiatives, research, communications, member services, or professional outreach.","/volunteer","View opportunities"],
  [Users,"Mentor and support others","Help students and emerging professionals reflect on goals, understand pathways, build confidence, and make responsible career decisions.","/pages/membership_community","Join the community"],
  [Mic2,"Speak or facilitate","Propose a webinar, panel, roundtable, masterclass, podcast conversation, event session, or moderated professional discussion.","/contact","Propose a contribution"],
  [FileText,"Write and publish","Contribute a practice article, case reflection, research insight, technical guide, career perspective, standard commentary, or professional resource.","/pages/thought_leadership","Explore publishing"],
  [Search,"Research and standards","Join consultations, evidence reviews, surveys, working groups, peer review, standards development, or future-practice investigations.","/pages/standards","Explore standards"],
  [BriefcaseBusiness,"Partner as an organisation","Collaborate on learning, research, events, careers, volunteering, sponsorship, standards, outreach, or professional capability programmes.","/pages/organizations","Organisation pathways"],
  [Network,"Build the community","Welcome members, contribute to conversations, connect peers, share responsible opportunities, and strengthen inclusive professional relationships.","/pages/join_the_conversation","Join the conversation"],
  [GraduationCap,"Support learning and certification","Develop questions, review learning content, share practice examples, support clinics, or contribute appropriate subject expertise.","/pages/certifications","Certification pathways"],
] as const;

const pathway = [
  ["01","Choose a contribution","Select an opportunity aligned with your expertise, interests, availability, development goals, and the value you can responsibly provide."],
  ["02","Review expectations","Check eligibility, scope, outputs, time commitment, location, access, conflicts, confidentiality, safeguarding, and required approvals."],
  ["03","Prepare your profile","Describe relevant knowledge, experience, motivation, evidence, availability, support needs, and any restrictions or competing interests."],
  ["04","Apply or propose","Use the linked dashboard workflow or contact form. Provide accurate, concise information that helps PCMO assess fit and risk."],
  ["05","Agree the assignment","Confirm purpose, responsibilities, authority, deliverables, schedule, communication, review, ownership, conduct, and escalation."],
  ["06","Deliver and record impact","Complete commitments, protect information, request feedback, submit evidence or hours where required, and capture outcomes and learning."],
] as const;

const contributionAreas = [
  [Target,"Professional practice","Project delivery, controls, PMO, governance, assurance, benefits, recovery, leadership, quality, risk, and stakeholder management."],
  [Scale,"Contracts and commercial","Strategy, procurement, formation, administration, payment, change, claims, records, negotiation, ethics, and closeout."],
  [Lightbulb,"Future practice","Responsible AI, data, automation, sustainability, new delivery models, emerging risks, innovation, and professional accountability."],
  [GraduationCap,"Education and careers","Learning design, assessment, mentoring, career pathways, employability, student support, capability, and continuing development."],
  [MessageCircle,"Community and events","Moderation, member welcome, networking, webinars, conferences, communications, outreach, partnerships, and inclusive participation."],
  [BookOpen,"Research and knowledge","Surveys, evidence reviews, case studies, standards, publications, peer review, editorial contribution, and knowledge organisation."],
] as const;

const principles = [
  ["Professional integrity","Represent competence, experience, credentials, authority, interests, availability, and completed work accurately."],
  ["Confidentiality and data protection","Protect personal, client, employer, project, contract, privileged, assessment, commercial, and unpublished information."],
  ["Respect and inclusion","Contribute without harassment, discrimination, intimidation, exploitation, retaliation, or exclusion."],
  ["Conflicts and independence","Disclose relevant financial, organisational, personal, professional, or intellectual interests before accepting work."],
  ["Quality and evidence","Use appropriate sources, distinguish evidence from opinion, follow review requirements, correct errors, and remain within competence."],
  ["Reliability and accountability","Understand the commitment, communicate early, keep records, meet agreed outputs, and escalate constraints or risks."],
] as const;

const faqs = [
  ["Who can get involved with PCMO?","Opportunities may be open to students, members, experienced professionals, specialists, educators, researchers, organisations, employers, partners, speakers, writers, mentors, and volunteers. Each opportunity defines its audience and requirements."],
  ["Do I need to be a paid member?","Some open consultations, public contributions, and community activities may not require paid membership. Member roles, restricted resources, formal appointments, or specialist programmes may have additional eligibility conditions."],
  ["Where can I find active volunteer opportunities?","Sign in and open Volunteer in the Student Portal. You can filter opportunities, view detailed requirements, apply, track status, submit eligible hours, and maintain an impact record."],
  ["How do I propose myself as a speaker or writer?","Send a concise proposal explaining the professional question, intended audience, relevance, your credentials, evidence base, proposed format, practical value, conflicts, commercial interests, and confidentiality restrictions."],
  ["Can volunteering support professional development?","A relevant assignment may support development when you record responsibilities, learning, application, evidence, feedback, and outcomes. Recognition remains subject to the rules of the relevant employer, certification, or professional body."],
  ["Will volunteer hours be recorded?","Approved volunteers can submit dated hour records through the portal where the assignment supports hour logging. Administrators review evidence before hours become approved in the impact record."],
  ["Can my organisation partner with PCMO?","Yes. Organisations can propose collaboration in learning, research, events, careers, standards, outreach, sponsorship, volunteering, or capability development. The arrangement must define value, responsibilities, interests, governance, data, branding, and outcomes."],
  ["Who owns contributed content?","Ownership, licence, attribution, review, editing, publication, withdrawal, confidentiality, and reuse should be agreed for the contribution. Do not submit material you are not authorised to share."],
  ["How are contributors selected?","Selection may consider relevance, competence, experience, evidence, quality, availability, diversity of perspective, conflicts, conduct, programme needs, capacity, and previous reliability."],
  ["What if I cannot complete an accepted commitment?","Inform the assigned PCMO contact early, explain the constraint factually, protect work and information, support a controlled handover where appropriate, and agree whether scope or timing can change."],
  ["Are contributors paid?","Many community and volunteer roles are unpaid. Paid, reimbursed, sponsored, or commercially contracted contributions must be explicitly agreed in writing before work begins."],
  ["How is contribution recognised?","Recognition may include verified hours, contributor attribution, acknowledgements, badges, references, certificates, community profiles, invitations, or development evidence, depending on the role and completed outcome."],
] as const;

const GetInvolvedHub = () => <div className="min-h-screen bg-white text-slate-800"><PublicNavigation active="connect"/><main>
  <section className="relative overflow-hidden bg-[#071f3b] px-6 py-24 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(220,38,38,.3),transparent_35%)]"/><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.22em] text-red-300">Get involved with PCMO</p><h1 className="mt-4 font-heading text-5xl font-extrabold leading-tight md:text-6xl">Turn professional experience into shared progress.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/70">Volunteer, mentor, speak, write, research, facilitate, partner, and help strengthen an inclusive global community for project and contract management.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/volunteer" className="inline-flex items-center gap-2 rounded bg-red-600 px-6 py-3 font-bold"><HandHeart className="h-4 w-4"/>Open volunteer portal</Link><a href="#pathways" className="rounded border border-white/25 px-6 py-3 font-bold">Explore pathways</a></div></div><div className="grid grid-cols-2 gap-4">{[[HandHeart,"Volunteer"],[Mic2,"Speak"],[FileText,"Publish"],[Network,"Partner"]].map(([Icon,label]) => {const CardIcon=Icon as typeof HandHeart;return <div key={String(label)} className="rounded-2xl border border-white/10 bg-white/5 p-7 text-center backdrop-blur"><CardIcon className="mx-auto h-10 w-10 text-red-400"/><p className="mt-4 font-bold">{String(label)}</p></div>})}</div></div></section>
  <section id="pathways" className="mx-auto max-w-7xl px-6 py-20"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-red-600">Contribution pathways</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">Choose how you want to contribute</h2><p className="mx-auto mt-4 max-w-3xl leading-7 text-slate-600">Start with the professional value you can offer, the outcome you want to support, and the commitment you can reliably make.</p></div><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{opportunities.map(([Icon,title,text,href,label]) => <article key={title} className="group flex flex-col rounded-2xl border p-7 shadow-sm transition hover:-translate-y-1 hover:border-red-300 hover:shadow-xl"><div className="grid h-12 w-12 place-items-center rounded-xl bg-[#0b3764] text-white group-hover:bg-red-600"><Icon className="h-6 w-6"/></div><h3 className="mt-5 text-xl font-extrabold text-[#0b3764]">{title}</h3><p className="mt-3 flex-1 leading-7 text-slate-600">{text}</p><Link to={href} className="mt-6 inline-flex items-center gap-2 font-bold text-red-600">{label}<ArrowRight className="h-4 w-4"/></Link></article>)}</div></section>
  <section className="bg-[#0b3764] px-6 py-20 text-white"><div className="mx-auto max-w-7xl"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-red-300">Participation journey</p><h2 className="mt-3 font-heading text-4xl font-extrabold">From interest to verified impact</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{pathway.map(([number,title,text]) => <article key={number} className="rounded-2xl border border-white/10 bg-white/5 p-7"><span className="text-4xl font-black text-red-400">{number}</span><h3 className="mt-3 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-white/65">{text}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-6 py-20"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-red-600">Areas of contribution</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">Bring expertise where it creates value</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{contributionAreas.map(([Icon,title,text]) => <article key={title} className="rounded-2xl border bg-slate-50 p-7"><Icon className="h-9 w-9 text-red-600"/><h3 className="mt-5 text-xl font-bold text-[#0b3764]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></section>
  <section className="bg-red-50 px-6 py-20"><div className="mx-auto max-w-7xl"><div className="text-center"><ShieldCheck className="mx-auto h-12 w-12 text-red-600"/><h2 className="mt-4 font-heading text-4xl font-extrabold text-[#0b3764]">Contributor standards</h2><p className="mx-auto mt-4 max-w-3xl leading-7 text-slate-600">Every contribution must protect the community, the profession, affected organisations, and the credibility of PCMO.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{principles.map(([title,text]) => <article key={title} className="rounded-2xl bg-white p-6 shadow-sm"><CheckCircle2 className="h-7 w-7 text-emerald-600"/><h3 className="mt-4 text-lg font-bold text-[#0b3764]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-4xl px-6 py-20"><h2 className="text-center font-heading text-4xl font-extrabold text-[#0b3764]">Get involved FAQs</h2><div className="mt-10 space-y-4">{faqs.map(([question,answer]) => <details key={question} className="group rounded-xl border bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5 font-bold text-[#0b3764]">{question}<ChevronDown className="h-5 w-5 shrink-0 transition group-open:rotate-180"/></summary><p className="border-t px-5 py-5 leading-7 text-slate-600">{answer}</p></details>)}</div></section>
  <section className="bg-red-600 px-6 py-16 text-center text-white"><Sparkles className="mx-auto h-11 w-11"/><h2 className="mt-4 font-heading text-4xl font-extrabold">Make your contribution count</h2><p className="mx-auto mt-4 max-w-2xl text-white/80">Choose a realistic pathway, understand the commitment, contribute professionally, and build a record of useful impact.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link to="/volunteer" className="rounded bg-white px-6 py-3 font-bold text-red-600">View opportunities</Link><Link to="/contact" className="rounded border border-white/40 px-6 py-3 font-bold">Propose a contribution</Link></div></section>
</main><PublicFooter/></div>;

export default GetInvolvedHub;
