import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, Check, Crown, GraduationCap, ShieldCheck, Sparkles, Users } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import PublicNavigation from "@/components/PublicNavigation";
import PublicFooter from "@/components/PublicFooter";

type Plan = { id: string; slug: string; name: string; description?: string; price: number; currency: string; billing_period: string; benefits?: string[] | string; featured_image?: string; page_eyebrow?: string; page_tagline?: string; page_audience?: string; page_content?: string; page_sections?: Array<{ title: string; text: string }> | string };

const meta: Record<string, { eyebrow: string; tagline: string; image: string; icon: typeof Users; audience: string }> = {
  "student-membership": { eyebrow: "For students", tagline: "Build your foundation. Find your direction. Join the profession.", image: "https://www.pcmo.world/website/spicimg/membership/1.jpeg", icon: GraduationCap, audience: "Students and early-career learners" },
  "individual-membership": { eyebrow: "For professionals", tagline: "The essential membership for continuous professional growth.", image: "https://www.pcmo.world/website/spicimg/membership/2.jpeg", icon: ShieldCheck, audience: "Independent working professionals" },
  "premium-membership": { eyebrow: "Premium pathway", tagline: "Accelerated learning, deeper insight, and priority professional access.", image: "https://www.pcmo.world/website/assets/img/about/4.jpg", icon: Crown, audience: "Ambitious professionals and future leaders" },
  "team-membership": { eyebrow: "For teams", tagline: "Shared learning goals with visibility, reporting, and premium resources.", image: "https://www.pcmo.world/website/spicimg/membership/3.jpeg", icon: Users, audience: "Teams of up to 10 professionals" },
  "corporate-membership": { eyebrow: "For organisations", tagline: "Organisation-wide capability development with analytics and control.", image: "https://www.pcmo.world/website/assets/img/banner/executives-paying-attention-digital-tablet.jpg", icon: Users, audience: "Organisations of up to 50 members" },
  "lifetime-membership": { eyebrow: "Permanent access", tagline: "One investment. Lifelong connection to professional opportunity.", image: "https://www.pcmo.world/website/spicimg/membership/retiree_membership.png", icon: Sparkles, audience: "Professionals seeking access without renewals" },
};

const MembershipPlanDetail = () => {
  const { slug = "" } = useParams();
  const query = useQuery({ queryKey: ["public-membership-plans"], queryFn: async () => { const response = await fetch("/api/public/membership-plans"); if (!response.ok) throw new Error("Membership plans are unavailable"); return response.json() as Promise<Plan[]>; } });
  const plan = query.data?.find(item => item.slug === slug);
  const defaults = meta[slug];
  const benefits = !plan ? [] : Array.isArray(plan.benefits) ? plan.benefits : (() => { try { return JSON.parse(plan.benefits || "[]") as string[]; } catch { return []; } })();

  if (query.isLoading) return <div className="grid min-h-screen place-items-center text-[#0b3764]">Loading membership…</div>;
  if (!plan || !defaults) return <div className="grid min-h-screen place-items-center"><div className="text-center"><h1 className="text-3xl font-bold text-[#0b3764]">Membership plan not found</h1><Link to="/pages/membership_and_networking" className="mt-5 inline-block text-red-600">View all plans</Link></div></div>;
  const content = { ...defaults, eyebrow: plan.page_eyebrow || defaults.eyebrow, tagline: plan.page_tagline || defaults.tagline, audience: plan.page_audience || defaults.audience };
  const Icon = content.icon;
  const price = Number(plan.price || 0);
  const monthly = plan.billing_period === "yearly" && price ? price / 12 : null;
  const sections = Array.isArray(plan.page_sections) ? plan.page_sections : (() => { try { return JSON.parse(plan.page_sections || "[]") as Array<{ title: string; text: string }>; } catch { return []; } })();

  return <div className="min-h-screen bg-white text-slate-800">
    <PublicNavigation active="membership" />
    <main>
      <section className="relative min-h-[560px] overflow-hidden bg-[#071f3b] text-white"><img src={plan.featured_image || content.image} alt={plan.name} className="absolute inset-0 h-full w-full object-cover opacity-30"/><div className="absolute inset-0 bg-gradient-to-r from-[#071f3b] via-[#0b3764]/90 to-red-950/55"/><div className="absolute -right-28 -top-28 h-96 w-96 animate-pulse rounded-full border-[60px] border-red-600/15"/><div className="relative mx-auto grid min-h-[560px] max-w-7xl gap-12 px-6 py-20 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div className="animate-in fade-in slide-in-from-left-6 duration-700"><Link to="/pages/membership_and_networking" className="inline-flex items-center gap-2 text-sm text-white/65 hover:text-white"><ArrowLeft className="h-4 w-4"/>All memberships</Link><p className="mt-8 text-sm font-bold uppercase tracking-[.2em] text-red-400">{content.eyebrow}</p><h1 className="mt-3 font-heading text-5xl font-extrabold md:text-6xl">{plan.name}</h1><p className="mt-5 max-w-2xl text-xl leading-8 text-white/75">{content.tagline}</p></div><div className="rounded-2xl border border-white/20 bg-white/10 p-8 shadow-2xl backdrop-blur"><Icon className="h-12 w-12 text-red-400"/><p className="mt-5 text-sm text-white/60">Membership investment</p><p className="mt-1 text-5xl font-extrabold">{price === 0 ? "Free" : `$${price.toLocaleString()}`}</p><p className="mt-2 text-sm text-white/60">{plan.billing_period === "one-time" ? "One-time payment · no renewal" : monthly ? `$${monthly.toFixed(2)} per month · billed yearly` : "No annual fee"}</p><Link to={`/login?mode=register&plan=${plan.slug}`} className="mt-7 flex items-center justify-center gap-2 rounded bg-red-600 px-6 py-4 font-bold transition hover:bg-red-700">Choose this membership <ArrowRight className="h-4 w-4"/></Link></div></div></section>
      <section className="mx-auto grid max-w-7xl gap-14 px-6 py-20 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div className="sticky top-28 rounded-2xl bg-slate-50 p-8"><p className="text-sm font-bold uppercase tracking-[.16em] text-red-600">Designed for</p><h2 className="mt-3 text-2xl font-extrabold text-[#0b3764]">{content.audience}</h2><p className="mt-5 leading-7 text-slate-600">{plan.description}</p><div className="mt-7 h-1 w-20 rounded bg-red-600"/></div><div><p className="text-sm font-bold uppercase tracking-[.16em] text-red-600">Included benefits</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">Everything you get</h2><div className="mt-8 grid gap-4 sm:grid-cols-2">{benefits.map((benefit, index) => <div key={benefit} className="group flex gap-4 rounded-xl border border-slate-200 p-5 transition hover:-translate-y-1 hover:border-red-300 hover:shadow-lg"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-emerald-50 text-emerald-600"><Check className="h-5 w-5"/></span><div><p className="text-xs font-bold text-slate-400">BENEFIT {String(index + 1).padStart(2, "0")}</p><p className="mt-1 font-bold text-[#0b3764]">{benefit}</p></div></div>)}</div></div></section>
      {(plan.page_content || sections.length > 0) && <section className="relative overflow-hidden bg-[#0b3764] px-6 py-20 text-white"><div className="absolute -right-24 -top-24 h-80 w-80 rounded-full border-[50px] border-red-600/10"/><div className="relative mx-auto max-w-7xl"><div className="max-w-4xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-red-400">How this membership helps</p><h2 className="mt-3 font-heading text-4xl font-extrabold">A pathway designed around your goals</h2>{plan.page_content && <p className="mt-6 text-lg leading-8 text-white/70">{plan.page_content}</p>}</div>{sections.length > 0 && <div className="mt-12 grid gap-5 md:grid-cols-3">{sections.map((section, index) => <article key={`${section.title}-${index}`} className="group rounded-2xl border border-white/15 bg-white/10 p-7 backdrop-blur transition duration-300 hover:-translate-y-2 hover:border-red-400/60 hover:bg-white/15"><span className="text-sm font-extrabold text-red-400">0{index + 1}</span><h3 className="mt-4 text-xl font-bold">{section.title}</h3><p className="mt-3 leading-7 text-white/65">{section.text}</p></article>)}</div>}</div></section>}
      <section className="bg-slate-50 px-6 py-16 text-center"><h2 className="font-heading text-3xl font-extrabold text-[#0b3764]">Ready to join with {plan.name}?</h2><p className="mx-auto mt-4 max-w-2xl text-slate-600">Create your PCMO account, select this plan, and begin your professional journey.</p><Link to={`/login?mode=register&plan=${plan.slug}`} className="mt-7 inline-flex items-center gap-2 rounded bg-red-600 px-7 py-4 font-bold text-white shadow-lg">Get started <ArrowRight className="h-5 w-5"/></Link></section>
    </main><PublicFooter />
  </div>;
};

export default MembershipPlanDetail;
