import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, CalendarDays, CheckCircle2, Clock3, MapPin, Network, ShieldCheck, Users } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import PublicFooter from "@/components/PublicFooter";
import PublicNavigation from "@/components/PublicNavigation";
import { api } from "@/lib/api";
import { fallbackNetworkingEvents, type PublicEvent } from "@/pages/NetworkingEventsHub";

const topicMap: Record<string,string[]> = {
  "Project Controls": ["Integrated scope, schedule, cost, risk, and change", "Contract obligations, notices, and decision records", "Forecast confidence and governance information", "Cross-functional controls and practical next steps"],
  "Contract Management": ["Notices, time limits, and factual communication", "Contemporaneous records and evidence quality", "Payment, variation, escalation, and claims avoidance", "Collaborative relationships with contractual discipline"],
  Governance: ["Sponsorship, authority, and decision rights", "Tolerances, escalation, and assurance", "Benefits ownership and ethical challenge", "Leadership through uncertainty and delivery pressure"],
  "Professional Growth": ["A concise and credible professional introduction", "Career pathways across project and contract management", "Peer, mentor, specialist, and employer conversations", "Development priorities and responsible follow-up"],
};

const NetworkingEventDetail = () => {
  const { id = "" } = useParams();
  const events = useQuery({queryKey:["public-events"],queryFn:()=>api<PublicEvent[]>("/api/public/events")});
  const event = events.data?.find(item => item.id === id) || fallbackNetworkingEvents.find(item => item.id === id);
  if (!event) return <div className="min-h-screen bg-white"><PublicNavigation active="membership"/><main className="mx-auto max-w-4xl px-6 py-24"><h1 className="font-heading text-4xl font-extrabold text-[#0b3764]">Event not found</h1><p className="mt-4 text-slate-600">This networking event is unavailable or has been removed.</p><Link to="/pages/upcoming_networking_events" className="mt-7 inline-flex items-center gap-2 font-bold text-red-600"><ArrowLeft className="h-4 w-4"/>Back to networking events</Link></main><PublicFooter/></div>;
  const topics = topicMap[event.category || ""] || ["Professional introductions and shared interests", "Current practice and participant experience", "Useful questions and moderated discussion", "Connections, learning, and responsible follow-up"];
  return <div className="min-h-screen bg-white text-slate-800"><PublicNavigation active="membership"/><main>
    <section className="bg-[#071f3b] px-6 py-20 text-white"><div className="mx-auto max-w-6xl"><Link to="/pages/upcoming_networking_events" className="inline-flex items-center gap-2 text-sm font-bold text-red-300"><ArrowLeft className="h-4 w-4"/>All networking events</Link><div className="mt-10 grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-start"><div><div className="flex flex-wrap gap-2 text-xs font-bold uppercase tracking-wider text-red-300"><span>{event.event_type}</span><span className="text-white/25">•</span><span>{event.category}</span><span className="text-white/25">•</span><span>{event.status}</span></div><h1 className="mt-4 font-heading text-4xl font-extrabold leading-tight md:text-5xl">{event.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/70">{event.description}</p></div><aside className="rounded-2xl border border-white/10 bg-white/5 p-7"><h2 className="text-xl font-bold">Event information</h2><div className="mt-5 space-y-4 text-sm text-white/75"><p className="flex items-center gap-3"><CalendarDays className="h-5 w-5 text-red-400"/>{new Date(`${event.event_date}T00:00:00`).toLocaleDateString("en-GB",{weekday:"long",day:"2-digit",month:"long",year:"numeric"})}</p><p className="flex items-center gap-3"><Clock3 className="h-5 w-5 text-red-400"/>{event.event_time?.slice(0,5) || "Time to be confirmed"}</p><p className="flex items-center gap-3"><MapPin className="h-5 w-5 text-red-400"/>{event.location || "Online"}</p><p className="flex items-center gap-3"><Users className="h-5 w-5 text-red-400"/>{event.attendees} registered · {event.capacity} capacity</p></div><Link to={`/events/${event.id}`} className="mt-7 flex items-center justify-center gap-2 rounded bg-red-600 px-5 py-3 font-bold">Register in Student Portal<ArrowRight className="h-4 w-4"/></Link></aside></div></div></section>
    <section className="mx-auto grid max-w-6xl gap-12 px-6 py-20 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-sm font-bold uppercase tracking-widest text-red-600">What the session explores</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">Focused professional conversations</h2><div className="mt-8 grid gap-4 sm:grid-cols-2">{topics.map(topic => <div key={topic} className="flex gap-3 rounded-xl border bg-slate-50 p-5"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-600"/><p className="font-semibold leading-6 text-[#0b3764]">{topic}</p></div>)}</div></div><aside className="rounded-2xl bg-red-50 p-8"><Network className="h-10 w-10 text-red-600"/><h2 className="mt-5 text-2xl font-extrabold text-[#0b3764]">Who should participate?</h2><p className="mt-4 leading-7 text-slate-600">Students, emerging professionals, project and contract practitioners, specialists, managers, mentors, employers, and leaders with a relevant interest in the event theme.</p><p className="mt-4 leading-7 text-slate-600">Prepare a short introduction, one clear objective, and two thoughtful questions. Never disclose restricted project, contract, employer, client, or personal information.</p></aside></section>
    <section className="bg-slate-50 px-6 py-20"><div className="mx-auto max-w-6xl"><div className="text-center"><ShieldCheck className="mx-auto h-11 w-11 text-red-600"/><h2 className="mt-4 font-heading text-4xl font-extrabold text-[#0b3764]">Participation guidance</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[["Before","Confirm your objective, update your profile, review the theme, and test access arrangements."],["During","Arrive on time, listen actively, make space for others, contribute concisely, and respect boundaries."],["After","Follow up personally, keep commitments, exchange value responsibly, and record relevant learning."]].map(([title,text]) => <article key={title} className="rounded-2xl bg-white p-7 shadow-sm"><h3 className="text-xl font-bold text-[#0b3764]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>
    <section className="bg-red-600 px-6 py-16 text-center text-white"><h2 className="font-heading text-4xl font-extrabold">Reserve your place</h2><p className="mx-auto mt-4 max-w-2xl text-white/80">Registration status and remaining capacity are managed through the Student Portal.</p><Link to={`/events/${event.id}`} className="mt-7 inline-flex items-center gap-2 rounded bg-white px-6 py-3 font-bold text-red-600">Open event registration<ArrowRight className="h-4 w-4"/></Link></section>
  </main><PublicFooter/></div>;
};

export default NetworkingEventDetail;
