import { useQuery } from "@tanstack/react-query";
import { ArrowRight, BriefcaseBusiness, CalendarCheck, CheckCircle2, ChevronDown, Clock3, Globe2, HeartHandshake, Lightbulb, MapPin, MessageCircle, Network, ShieldCheck, Sparkles, Target, UserCheck, Users, Video } from "lucide-react";
import { Link } from "react-router-dom";
import PublicFooter from "@/components/PublicFooter";
import PublicNavigation from "@/components/PublicNavigation";
import { api } from "@/lib/api";

export type PublicEvent = { id:string; title:string; description?:string; event_type:string; category?:string; event_date:string; event_time?:string; location?:string; capacity:number; status:string; attendees:number };

const formats = [
  [Video,"Virtual networking rooms","Accessible online sessions with structured introductions, themed breakout conversations, useful prompts, and clear follow-up opportunities."],
  [MessageCircle,"Industry roundtables","Small moderated groups comparing current challenges, evidence, professional judgement, controls, and lessons across sectors."],
  [Users,"Member meetups","Welcoming community-led gatherings for local introductions, peer relationships, career conversations, and shared professional interests."],
  [BriefcaseBusiness,"Career connection events","Meet recruiters, employers, mentors, leaders, and peers while strengthening how you communicate capability and professional value."],
  [Lightbulb,"Expert exchange sessions","Connect around a focused technical or leadership question with experienced practitioners and participants who share the interest."],
  [Globe2,"Cross-border community forums","Build relationships across regions while learning how sector, contract, law, culture, scale, and delivery context shape practice."],
] as const;

const goals = [
  [Target,"Set one purpose","Decide whether you want to meet peers, find a mentor, explore a specialism, understand a sector, identify opportunities, or contribute expertise."],
  [UserCheck,"Prepare your introduction","Explain who you are, what you work on or study, what interests you, and the useful conversation you hope to have—without reciting your full CV."],
  [MessageCircle,"Ask better questions","Use open, relevant questions that invite experience and context. Listen carefully before introducing your own example or request."],
  [HeartHandshake,"Offer value first","Share a useful perspective, reference, introduction, encouragement, question, or follow-up instead of approaching every connection as a transaction."],
  [Network,"Exchange details responsibly","Connect through agreed professional channels, respect boundaries, avoid unsolicited promotion, and protect personal or confidential information."],
  [CheckCircle2,"Follow through","Send a brief personalised follow-up, keep commitments, record relevant learning, and continue only where there is mutual professional value."],
] as const;

const pathway = [
  ["01","Discover the right room","Review the theme, audience, format, speakers, participant profile, location, capacity, time zone, and intended outcomes."],
  ["02","Register through My Events","Sign in, reserve your place, check the status and capacity, and cancel early if your plans change."],
  ["03","Build your profile","Update your professional interests, experience, goals, credentials, location, and preferred ways to contribute or connect."],
  ["04","Participate intentionally","Arrive on time, join the activity, make space for others, take concise notes, and protect restricted information."],
  ["05","Create useful follow-up","Reference the conversation, explain the reason for reconnecting, offer something relevant, and agree a proportionate next step."],
  ["06","Grow the relationship","Stay reliable, exchange value over time, introduce others appropriately, and allow professional trust to develop naturally."],
] as const;

const standards = [
  ["Respect and inclusion","Welcome varied career stages, disciplines, sectors, locations, identities, and professional perspectives without harassment or exclusion."],
  ["Consent and boundaries","Do not pressure participants to share contact details, accept invitations, discuss personal matters, or continue a professional relationship."],
  ["No undisclosed solicitation","Declare relevant commercial interests and avoid spam, aggressive selling, recruitment misrepresentation, or unauthorised data collection."],
  ["Confidentiality","Do not disclose client, employer, project, contract, personal, privileged, or commercially restricted information during introductions or discussion."],
  ["Accurate representation","Describe roles, credentials, achievements, organisations, opportunities, and authority honestly; distinguish personal views from official positions."],
  ["Constructive contribution","Listen, make space, stay relevant, challenge ideas respectfully, keep commitments, and report behaviour that threatens participant safety."],
] as const;

const faqs = [
  ["How do I register for a networking event?","Sign in, open My Events, select an available networking event, and choose Register. The same database record controls availability, capacity, and registration status."],
  ["Are networking events available to free members?","Selected virtual and community events may be available to free members. Some specialist, limited-capacity, partner, or in-person events may require an eligible membership, invitation, or fee."],
  ["I am a student or early-career professional. Can I participate?","Yes. PCMO networking is designed to include students, emerging professionals, experienced practitioners, specialists, leaders, educators, and retired professionals where the event audience permits."],
  ["Do I need to prepare anything?","Prepare a short introduction, one networking objective, two relevant questions, and an updated community profile. Review the event theme and participation guidance before joining."],
  ["Will participant contact details be shared?","Contact details should only be exchanged with appropriate consent. Do not copy, scrape, publish, sell, or reuse participant information for unrelated communication."],
  ["Can recruiters and employers attend?","Yes, where the event format permits. Opportunities and organisational representation must be accurate, relevant, transparent, and consistent with event conduct requirements."],
  ["Can I promote my company or services?","Only where promotion is explicitly part of the format or approved by PCMO. Disclose relevant interests and focus on useful professional contribution rather than unsolicited selling."],
  ["What should I do if an interaction is inappropriate?","End the interaction where necessary, retain relevant evidence, use available event moderation or reporting channels, and contact PCMO with a clear factual account."],
  ["What happens if I cannot attend?","Cancel through My Events as early as possible so capacity can be released. Check for another event with a similar theme or format."],
  ["How can I host or propose a networking event?","Send the proposed audience, professional purpose, format, facilitation plan, expected outcomes, location or platform, accessibility needs, capacity, conflicts, sponsorship, and conduct controls."],
] as const;

export const fallbackNetworkingEvents: PublicEvent[] = [
  {id:"8f600000-0000-4000-8000-000000000001",title:"Integrated Project and Contract Controls Forum",description:"A practical interactive forum connecting scope, schedule, cost, risk, change, obligations, notices, records, and forecasts into one decision-useful control environment.",event_type:"Forum",category:"Project Controls",event_date:"2026-08-28",event_time:"14:00:00",location:"Virtual event",capacity:150,status:"scheduled",attendees:0},
  {id:"8f600000-0000-4000-8000-000000000003",title:"Contract Administration in Practice Roundtable",description:"A moderated discussion on notices, records, payment, change, relationships, escalation, claims avoidance, commercial judgement, and disciplined contract closeout.",event_type:"Roundtable",category:"Contract Management",event_date:"2026-10-08",event_time:"15:00:00",location:"Virtual event",capacity:80,status:"scheduled",attendees:0},
  {id:"8f600000-0000-4000-8000-000000000004",title:"Project Leadership and Governance Forum",description:"An advanced forum covering sponsorship, authority, decision rights, tolerances, assurance, benefits ownership, ethical challenge, and leadership through uncertainty.",event_type:"Forum",category:"Governance",event_date:"2026-11-12",event_time:"10:00:00",location:"Abu Dhabi + Online",capacity:180,status:"scheduled",attendees:0},
  {id:"8f600000-0000-4000-8000-000000000005",title:"Early Career Project and Contract Management Networking Lab",description:"A structured networking and capability session for students and early-career professionals to practise introductions, discuss career pathways, meet peers, and identify development priorities.",event_type:"Networking",category:"Professional Growth",event_date:"2026-12-03",event_time:"16:00:00",location:"Virtual event",capacity:120,status:"scheduled",attendees:0},
];

const NetworkingEventsHub = () => {
  const events = useQuery({queryKey:["public-events"],queryFn:()=>api<PublicEvent[]>("/api/public/events")});
  const liveNetworkingEvents = events.data?.filter(event => /network|roundtable|forum|meetup/i.test(`${event.event_type} ${event.title}`));
  const networkingEvents = liveNetworkingEvents?.length ? liveNetworkingEvents : fallbackNetworkingEvents;
  return <div className="min-h-screen bg-white text-slate-800"><PublicNavigation active="membership"/><main>
    <section className="relative overflow-hidden bg-[#071f3b] px-6 py-24 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(220,38,38,.3),transparent_35%)]"/><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.22em] text-red-300">Meet · Learn · Connect</p><h1 className="mt-4 font-heading text-5xl font-extrabold leading-tight md:text-6xl">Networking events with a professional purpose.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/70">Meet peers, mentors, specialists, employers, leaders, and collaborators through structured events designed to turn introductions into useful professional relationships.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/networking-events" className="inline-flex items-center gap-2 rounded bg-red-600 px-6 py-3 font-bold"><CalendarCheck className="h-4 w-4"/>View and register</Link><a href="#upcoming" className="rounded border border-white/25 px-6 py-3 font-bold">Upcoming sessions</a></div></div><div className="relative grid h-80 place-items-center rounded-3xl border border-white/10 bg-white/5 backdrop-blur"><div className="absolute h-64 w-64 rounded-full border border-dashed border-white/20"/><div className="absolute h-44 w-44 rounded-full border border-red-400/40"/><Network className="relative h-24 w-24 text-red-400"/><Users className="absolute left-12 top-12 h-9 w-9 text-white/35"/><MessageCircle className="absolute bottom-14 right-14 h-10 w-10 text-white/35"/></div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-20"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-red-600">Networking formats</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">Choose the environment that fits your objective</h2></div><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{formats.map(([Icon,title,text]) => <article key={title} className="group rounded-2xl border p-7 shadow-sm transition hover:-translate-y-1 hover:border-red-300 hover:shadow-xl"><div className="grid h-12 w-12 place-items-center rounded-xl bg-[#0b3764] text-white group-hover:bg-red-600"><Icon className="h-6 w-6"/></div><h3 className="mt-5 text-xl font-extrabold text-[#0b3764]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></section>
    <section id="upcoming" className="bg-slate-50 px-6 py-20"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-red-600">Live database programme</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">Upcoming networking opportunities</h2></div><Link to="/networking-events" className="inline-flex items-center gap-2 font-bold text-red-600">Registration and availability<ArrowRight className="h-4 w-4"/></Link></div><div className="mt-10 grid gap-6 lg:grid-cols-2">{networkingEvents.map(event => <article key={event.id} className="rounded-2xl border bg-white p-7 shadow-sm"><div className="flex flex-wrap gap-2 text-xs font-bold uppercase tracking-wider text-red-600"><span>{new Date(`${event.event_date}T00:00:00`).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"})}</span><span className="text-slate-300">•</span><span>{event.event_time?.slice(0,5) || "TBA"}</span><span className="text-slate-300">•</span><span>{event.category}</span></div><h3 className="mt-3 text-xl font-extrabold text-[#0b3764]">{event.title}</h3><p className="mt-3 leading-7 text-slate-600">{event.description}</p><div className="mt-5 flex flex-wrap justify-between gap-3 border-t pt-4 text-xs text-slate-500"><span className="flex items-center gap-1"><MapPin className="h-4 w-4"/>{event.location}</span><span className="flex items-center gap-1"><Users className="h-4 w-4"/>{event.attendees} / {event.capacity} registered</span></div><Link to={`/pages/networking-events/${event.id}`} className="mt-5 inline-flex items-center gap-2 font-bold text-red-600">View detailed page<ArrowRight className="h-4 w-4"/></Link></article>)}</div></div></section>
    <section className="bg-[#0b3764] px-6 py-20 text-white"><div className="mx-auto max-w-7xl"><div className="text-center"><Sparkles className="mx-auto h-11 w-11 text-red-400"/><h2 className="mt-4 font-heading text-4xl font-extrabold">Network with intention</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{goals.map(([Icon,title,text]) => <article key={title} className="rounded-2xl border border-white/10 bg-white/5 p-7"><Icon className="h-8 w-8 text-red-400"/><h3 className="mt-4 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-white/65">{text}</p></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-20"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-red-600">Relationship pathway</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">From registration to a trusted connection</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{pathway.map(([number,title,text]) => <article key={number} className="rounded-2xl border bg-slate-50 p-7"><span className="text-4xl font-black text-red-600">{number}</span><h3 className="mt-3 text-xl font-bold text-[#0b3764]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></section>
    <section className="bg-red-50 px-6 py-20"><div className="mx-auto max-w-7xl"><div className="text-center"><ShieldCheck className="mx-auto h-12 w-12 text-red-600"/><h2 className="mt-4 font-heading text-4xl font-extrabold text-[#0b3764]">Professional networking standards</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{standards.map(([title,text]) => <article key={title} className="rounded-2xl bg-white p-6 shadow-sm"><CheckCircle2 className="h-7 w-7 text-emerald-600"/><h3 className="mt-4 text-lg font-bold text-[#0b3764]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>
    <section className="mx-auto max-w-4xl px-6 py-20"><h2 className="text-center font-heading text-4xl font-extrabold text-[#0b3764]">Networking event FAQs</h2><div className="mt-10 space-y-4">{faqs.map(([question,answer]) => <details key={question} className="group rounded-xl border bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5 font-bold text-[#0b3764]">{question}<ChevronDown className="h-5 w-5 shrink-0 transition group-open:rotate-180"/></summary><p className="border-t px-5 py-5 leading-7 text-slate-600">{answer}</p></details>)}</div></section>
    <section className="bg-red-600 px-6 py-16 text-center text-white"><Network className="mx-auto h-11 w-11"/><h2 className="mt-4 font-heading text-4xl font-extrabold">Make your next connection count</h2><p className="mx-auto mt-4 max-w-2xl text-white/80">Choose an event aligned with your objective, participate professionally, and follow through with purpose.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link to="/networking-events" className="rounded bg-white px-6 py-3 font-bold text-red-600">Open My Events</Link><Link to="/community-profile" className="rounded border border-white/40 px-6 py-3 font-bold">Update community profile</Link></div></section>
  </main><PublicFooter/></div>;
};

export default NetworkingEventsHub;
