import { Link } from "react-router-dom";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { ArrowRight, Award, BookOpen, BriefcaseBusiness, Building2, CalendarDays, CheckCircle2, Clock, Hash, HeartHandshake, Lightbulb, MapPin, MessageCircle, Mic2, Network, PenLine, Quote, Search, Send, ShieldCheck, Sparkles, TrendingUp, UserCheck, Users, Video } from "lucide-react";
import PublicFooter from "@/components/PublicFooter";
import PublicNavigation from "@/components/PublicNavigation";
import { api } from "@/lib/api";
import { useAuth } from "@/hooks/useAuth";

type PageKey = "membership-networking" | "membership-community" | "job-community" | "chat-rooms" | "networking-events" | "conversation";
type ExpertRoom = { id: string; title: string; topic?: string; description?: string; expert_name: string; expert_role?: string; format: string; scheduled_at: string; duration_minutes: number; capacity: number; reserved_count: number; user_reserved: number };
type CommunityRoom = { id: string; slug: string; name: string; description?: string; category?: string; moderator_name?: string; access_level: string; featured: number; message_count: number; participant_count: number; last_activity?: string | null };
type Conversation = { id: string; title: string; content?: string; category: string; reply_count: number; contributor_count: number; views: number; likes: number };

const pages = {
  "membership-networking": { eyebrow: "Connect. Contribute. Grow.", title: "Membership & Networking", intro: "Membership is more than access. It is your pathway into a trusted professional network where shared knowledge creates stronger careers and better outcomes.", icon: Network, action: "Compare memberships", href: "/pages/compare_all_memberships", cards: [["A community that knows your field", "Connect with people who understand the realities of projects, contracts, procurement, and delivery."], ["Access with purpose", "Move from introductions to useful conversations, shared learning, mentorship, and collaboration."], ["A network that grows with you", "Find relevant support at every stage—from student and early career to leadership and retirement."]] },
  "membership-community": { eyebrow: "Networking at PCMO", title: "Membership Community", intro: "Meet the professionals, students, mentors, and industry leaders who make PCMO a global place to learn, exchange ideas, and grow.", icon: Users, action: "Explore membership", href: "/pages/membership_and_networking", cards: [["Find your people", "Build meaningful relationships across project, contracts, energy, infrastructure, and technology."], ["Share expertise", "Exchange practical experience, lessons learned, and useful perspectives with peers."], ["Grow together", "Discover mentors, collaborators, and opportunities that support your next professional step."]] },
  "job-community": { eyebrow: "Careers & opportunity", title: "Job Community", intro: "A focused career network connecting PCMO members with opportunities, practical guidance, and professionals who understand the industry.", icon: BriefcaseBusiness, action: "Join the community", href: "/login?mode=register", cards: [["Discover opportunities", "Stay connected to project and contracts roles shared across the PCMO network."], ["Strengthen your profile", "Learn how to present your skills, experience, and certifications with confidence."], ["Connect with employers", "Build relationships with organisations and leaders seeking capable professionals."]] },
  "chat-rooms": { eyebrow: "Member conversations", title: "Community Chat Rooms", intro: "Step into focused spaces for real-time discussion, peer support, knowledge sharing, and professional connection.", icon: MessageCircle, action: "Enter the community", href: "/login", cards: [["Project management", "Discuss delivery, controls, leadership, risk, planning, and lessons from the field."], ["Contracts community", "Exchange perspectives on procurement, claims, negotiation, and contract administration."], ["Students & early careers", "Ask questions, meet peers, and get support as you begin your professional journey."]] },
  "networking-events": { eyebrow: "Meet. Learn. Connect.", title: "Upcoming Networking Events", intro: "Join webinars, roundtables, meetups, and community sessions designed to turn professional introductions into lasting connections.", icon: CalendarDays, action: "View all events", href: "/events", cards: [["Virtual networking", "Join accessible online sessions with peers and experts from across the PCMO community."], ["Industry roundtables", "Explore current challenges through focused, interactive conversations led by practitioners."], ["Member meetups", "Create stronger professional relationships in welcoming, community-led gatherings."]] },
  conversation: { eyebrow: "Your voice matters", title: "Join the Conversation", intro: "Bring your experience, questions, and ideas to a professional community built on generous knowledge sharing and respectful dialogue.", icon: Send, action: "Start a conversation", href: "/community-profile", cards: [["Ask a question", "Get practical perspectives from people who have faced similar professional challenges."], ["Share an insight", "Contribute a lesson, tool, or viewpoint that can help another member move forward."], ["Build your network", "Follow conversations, connect with contributors, and turn discussion into collaboration."]] },
} as const;

const NetworkingPage = ({ page }: { page: PageKey }) => {
  const current = pages[page];
  const Icon = current.icon;
  const { user } = useAuth();
  const [jobKeyword, setJobKeyword] = useState("");
  const [jobLocation, setJobLocation] = useState("");
  const queryClient = useQueryClient();
  const expertRooms = useQuery({ queryKey: ["public-expert-rooms", user?.id], queryFn: () => api<{ rows: ExpertRoom[] }>("/api/public/expert-rooms"), enabled: page === "membership-community" });
  const communityRooms = useQuery({ queryKey: ["public-chat-rooms"], queryFn: () => api<{ rows: CommunityRoom[] }>("/api/public/chat-rooms"), enabled: page === "chat-rooms" });
  const conversations = useQuery({ queryKey: ["public-conversations"], queryFn: () => api<{ featured: Conversation | null; trending: Conversation[] }>("/api/public/conversations"), enabled: page === "conversation" });
  const reserveRoom = useMutation({
    mutationFn: ({ id, reserved }: { id: string; reserved: boolean }) => api(`/api/expert-rooms/${id}/reserve`, { method: reserved ? "DELETE" : "POST" }),
    onSuccess: (_data, variables) => { toast.success(variables.reserved ? "Reservation cancelled" : "Your seat is confirmed"); void queryClient.invalidateQueries({ queryKey: ["public-expert-rooms"] }); },
    onError: (error: Error) => toast.error(error.message),
  });
  const handleReservation = (room: ExpertRoom) => {
    if (!user) { window.location.href = `/login?redirect=${encodeURIComponent("/pages/membership_community")}`; return; }
    reserveRoom.mutate({ id: room.id, reserved: Boolean(room.user_reserved) });
  };
  const searchJobs = (event: React.FormEvent) => {
    event.preventDefault();
    const target = new URL("https://talentspecialist.org/all-job-search.html");
    if (jobKeyword.trim()) target.searchParams.set("keyword", jobKeyword.trim());
    if (jobLocation.trim()) target.searchParams.set("location", jobLocation.trim());
    window.open(target.toString(), "_blank", "noopener,noreferrer");
  };
  return <div className="min-h-screen bg-white text-slate-900">
    <PublicNavigation active="membership" />
    <main>
      <section className="relative overflow-hidden bg-[#071f3b] px-6 py-24 text-white"><div className="absolute inset-0 opacity-20 [background-image:radial-gradient(circle_at_20%_20%,#ef4444_0,transparent_28%),radial-gradient(circle_at_80%_70%,#3b82f6_0,transparent_28%)]"/><div className="absolute -right-20 -top-20 h-72 w-72 animate-pulse rounded-full border-[45px] border-red-500/10"/><div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><div className="animate-in fade-in slide-in-from-left-8 duration-700"><p className="text-sm font-bold uppercase tracking-[.22em] text-red-400">{current.eyebrow}</p><h1 className="mt-4 max-w-3xl font-heading text-5xl font-extrabold leading-tight md:text-6xl">{current.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70">{current.intro}</p><Link to={current.href} className="mt-9 inline-flex items-center gap-2 rounded bg-red-600 px-6 py-4 font-bold shadow-xl transition duration-300 hover:-translate-y-1 hover:bg-red-700 hover:shadow-red-950/40">{current.action}<ArrowRight className="h-5 w-5 transition group-hover:translate-x-1"/></Link></div><div className="relative mx-auto grid h-80 w-full max-w-lg animate-in zoom-in-90 fade-in place-items-center rounded-[2rem] border border-white/15 bg-white/10 shadow-2xl duration-700 backdrop-blur"><div className="absolute h-64 w-64 animate-[spin_24s_linear_infinite] rounded-full border border-dashed border-white/20"/><div className="absolute h-44 w-44 animate-pulse rounded-full border border-red-400/40"/><Icon className="relative h-24 w-24 text-red-400"/><Network className="absolute left-10 top-10 h-8 w-8 animate-bounce text-white/35 [animation-duration:3s]"/><MessageCircle className="absolute bottom-12 right-12 h-9 w-9 animate-bounce text-white/35 [animation-delay:1s] [animation-duration:3s]"/></div></div></section>
      <section className="px-6 py-20"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-bold uppercase tracking-[.2em] text-red-600">Connect with purpose</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">Where professional relationships become opportunities</h2></div><div className="mt-12 grid gap-6 md:grid-cols-3">{current.cards.map(([title, text], index) => <article key={title} className="group rounded-2xl border border-slate-200 bg-white p-7 shadow-sm transition duration-300 hover:-translate-y-2 hover:border-red-200 hover:shadow-xl"><span className="grid h-12 w-12 place-items-center rounded-xl bg-red-50 font-extrabold text-red-600">0{index + 1}</span><h3 className="mt-6 text-xl font-bold text-[#0b3764]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>
      <section className="overflow-hidden bg-[#0b3764] px-6 py-16 text-white"><div className="mx-auto grid max-w-6xl gap-8 text-center sm:grid-cols-3">{[["500+", "Community members"], ["15+", "Countries represented"], ["50+", "Learning and networking opportunities"]].map(([value, label], index) => <div key={label} className="group border-white/10 sm:border-r sm:last:border-0"><p className="font-heading text-5xl font-extrabold text-red-400 transition duration-500 group-hover:scale-110">{value}</p><p className="mt-2 text-sm uppercase tracking-widest text-white/60">{label}</p></div>)}</div></section>
      <section className="px-6 py-20"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-2"><div className="relative min-h-96 overflow-hidden rounded-3xl bg-slate-100 p-8 shadow-xl"><div className="absolute -left-16 -top-16 h-56 w-56 rounded-full bg-red-600/10"/><div className="absolute -bottom-20 -right-16 h-72 w-72 rounded-full bg-[#0b3764]/10"/><div className="relative grid h-full place-items-center rounded-2xl border border-slate-200 bg-white/70 p-10 text-center backdrop-blur"><Icon className="h-20 w-20 text-red-600"/><p className="mt-6 font-heading text-2xl font-extrabold text-[#0b3764]">Your next connection could change your next chapter.</p></div></div><div><p className="text-sm font-bold uppercase tracking-[.2em] text-red-600">How it works</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">From joining to belonging</h2><div className="mt-8 space-y-7">{[["01", "Create your profile", "Introduce your experience, interests, and professional goals."], ["02", "Enter the right spaces", "Find communities, conversations, and events relevant to your journey."], ["03", "Participate and grow", "Ask, contribute, follow up, and build relationships that last."]].map(([number, title, text]) => <div key={number} className="group flex gap-5"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#0b3764] text-sm font-bold text-white transition group-hover:bg-red-600">{number}</span><div><h3 className="text-lg font-bold text-[#0b3764]">{title}</h3><p className="mt-1 leading-7 text-slate-600">{text}</p></div></div>)}</div></div></div></section>
      <section className="bg-slate-50 px-6 py-20"><div className="mx-auto max-w-5xl text-center"><p className="text-6xl font-serif text-red-600">“</p><blockquote className="mt-2 font-heading text-2xl font-bold leading-10 text-[#0b3764] md:text-3xl">PCMO turns professional networking into a welcoming exchange of knowledge, encouragement, and real opportunity.</blockquote><p className="mt-5 text-sm font-bold uppercase tracking-widest text-slate-500">The PCMO community experience</p></div></section>
      {page === "membership-community" && <>
        <section className="px-6 py-20"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-red-600">Expert rooms</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">Go beyond networking. Learn with experts.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">Join focused rooms led by experienced practitioners. Ask real questions, explore live cases, and leave with practical next steps.</p></div><span className="font-bold text-red-600">Live availability</span></div>
          {expertRooms.isLoading ? <div className="mt-10 grid gap-6 lg:grid-cols-3">{[1,2,3].map(item => <div key={item} className="h-96 animate-pulse rounded-2xl bg-slate-100"/>)}</div> : expertRooms.error ? <p className="mt-10 rounded-xl bg-red-50 p-5 text-red-700">Expert rooms are temporarily unavailable.</p> : <div className="mt-10 grid gap-6 lg:grid-cols-3">{expertRooms.data?.rows.map(room => { const remaining = Math.max(0, Number(room.capacity) - Number(room.reserved_count)); const reserved = Boolean(room.user_reserved); return <article key={room.id} className="group relative overflow-hidden rounded-2xl border border-slate-200 bg-white p-7 shadow-sm transition duration-300 hover:-translate-y-2 hover:shadow-2xl"><div className="absolute right-0 top-0 h-24 w-24 rounded-bl-full bg-red-50 transition group-hover:bg-red-100"/><Video className="relative h-9 w-9 text-red-600"/><div className="mt-6 flex items-center justify-between gap-3"><span className="inline-flex rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{room.format}</span><span className={`text-xs font-bold ${remaining < 5 ? "text-red-600" : "text-slate-500"}`}>{remaining} seats left</span></div><h3 className="mt-4 text-xl font-extrabold text-[#0b3764]">{room.title}</h3><p className="mt-2 text-sm text-slate-500">{room.topic}</p><div className="my-5 h-px bg-slate-100"/><p className="font-bold text-slate-800">{room.expert_name}</p><p className="mt-1 text-xs text-slate-500">{room.expert_role}</p><p className="mt-5 flex items-center gap-2 text-sm font-semibold text-[#0b3764]"><Clock className="h-4 w-4 text-red-600"/>{new Date(room.scheduled_at).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })} · {room.duration_minutes} min</p><button disabled={reserveRoom.isPending || (!reserved && remaining === 0)} onClick={() => handleReservation(room)} className={`mt-6 flex w-full items-center justify-center gap-2 rounded-lg px-4 py-3 text-sm font-bold text-white transition disabled:cursor-not-allowed disabled:opacity-50 ${reserved ? "bg-emerald-600 hover:bg-red-600" : "bg-[#0b3764] hover:bg-red-600"}`}>{reserved ? "Seat reserved · Cancel" : remaining ? "Reserve a seat" : "Room full"}<ArrowRight className="h-4 w-4"/></button></article>})}</div>}
        </div></section>
        <section className="bg-[#071f3b] px-6 py-20 text-white"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><Sparkles className="h-11 w-11 text-red-400"/><p className="mt-6 text-sm font-bold uppercase tracking-[.2em] text-red-400">Smart connections</p><h2 className="mt-3 font-heading text-4xl font-extrabold">Find the right mentor, peer, or specialist.</h2><p className="mt-5 leading-8 text-white/65">Tell us what you want to learn or solve. PCMO helps you discover members with aligned experience, interests, and availability.</p><Link to="/community-profile" className="mt-8 inline-flex items-center gap-2 rounded bg-red-600 px-6 py-4 font-bold">Build your community profile <ArrowRight className="h-5 w-5"/></Link></div><div className="grid gap-4 sm:grid-cols-2">{[[UserCheck, "Mentor matching", "Connect with experienced professionals for focused career guidance."], [MessageCircle, "Peer problem-solving", "Form small circles around shared challenges and objectives."], [Award, "Expert office hours", "Book short group sessions with subject-matter specialists."], [Network, "Collaboration finder", "Meet members interested in research, speaking, and projects."]].map(([MatchIcon, title, text]) => { const MIcon = MatchIcon as typeof UserCheck; return <article key={String(title)} className="rounded-2xl border border-white/10 bg-white/5 p-6 transition hover:-translate-y-1 hover:border-red-400/50 hover:bg-white/10"><MIcon className="h-8 w-8 text-red-400"/><h3 className="mt-4 text-lg font-bold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-white/55">{String(text)}</p></article>})}</div></div></section>
      </>}
      {page === "job-community" && <>
        <section className="px-6 py-20"><div className="mx-auto max-w-7xl"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[.2em] text-red-600">Opportunity board</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">Roles selected for the PCMO community</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-slate-600">Discover relevant project and contracts opportunities and connect with the people behind them.</p></div><form onSubmit={searchJobs} className="mx-auto mt-9 flex max-w-4xl flex-col gap-3 rounded-2xl border bg-white p-3 shadow-lg sm:flex-row"><label className="flex flex-1 items-center gap-3 px-3"><Search className="h-5 w-5 shrink-0 text-slate-400"/><span className="sr-only">Job title, skill, or keyword</span><input value={jobKeyword} onChange={event => setJobKeyword(event.target.value)} placeholder="Job title, skill, or keyword" className="w-full bg-transparent py-2 text-sm text-slate-700 outline-none placeholder:text-slate-400"/></label><div className="hidden h-9 w-px bg-slate-200 sm:block"/><label className="flex flex-1 items-center gap-3 px-3"><MapPin className="h-5 w-5 shrink-0 text-slate-400"/><span className="sr-only">Location or remote</span><input value={jobLocation} onChange={event => setJobLocation(event.target.value)} placeholder="Location or remote" className="w-full bg-transparent py-2 text-sm text-slate-700 outline-none placeholder:text-slate-400"/></label><button type="submit" className="rounded-xl bg-red-600 px-7 py-3 text-sm font-bold text-white transition hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-300">Search jobs</button></form><p className="mx-auto mt-3 max-w-4xl text-center text-xs text-slate-500">Search results open securely on Talent Specialist.</p><div className="mt-10 grid gap-5">{[
          ["Senior Contracts Manager", "Global Infrastructure Partners", "Dubai, UAE", "Full time", "Featured", ["FIDIC", "Claims", "Negotiation"], "senior-contracts-manager"],
          ["Project Controls Engineer", "NorthStar Energy", "Hybrid · Abu Dhabi", "Full time", "New", ["Primavera P6", "EVM", "Risk"], "project-controls-engineer"],
          ["PMO Analyst", "Crestline Consulting", "Remote", "Contract", "Member match", ["Reporting", "Governance", "Power BI"], "pmo-analyst"],
        ].map(([role, company, location, kind, badge, skills, slug]) => <article key={String(role)} className="group grid gap-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition duration-300 hover:border-red-200 hover:shadow-xl md:grid-cols-[auto_1fr_auto] md:items-center"><div className="grid h-14 w-14 place-items-center rounded-xl bg-slate-100 text-[#0b3764] transition group-hover:bg-[#0b3764] group-hover:text-white"><Building2 className="h-7 w-7"/></div><div><div className="flex flex-wrap items-center gap-3"><h3 className="text-xl font-extrabold text-[#0b3764]">{String(role)}</h3><span className="rounded-full bg-red-50 px-3 py-1 text-xs font-bold text-red-600">{String(badge)}</span></div><p className="mt-2 font-semibold text-slate-600">{String(company)}</p><div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-500"><span className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5"/>{String(location)}</span><span className="flex items-center gap-1"><Clock className="h-3.5 w-3.5"/>{String(kind)}</span></div><div className="mt-4 flex flex-wrap gap-2">{(skills as readonly string[]).map(skill => <span key={skill} className="rounded bg-slate-100 px-2.5 py-1 text-xs text-slate-600">{skill}</span>)}</div></div><Link to={`/jobs/${String(slug)}`} className="inline-flex items-center justify-center gap-2 rounded-lg border border-[#0b3764] px-5 py-3 text-sm font-bold text-[#0b3764] transition hover:bg-[#0b3764] hover:text-white">View role <ArrowRight className="h-4 w-4"/></Link></article>)}<div className="mt-4 text-center"><a href="https://talentspecialist.org/all-job-search.html" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-[#0b3764] px-7 py-4 font-bold text-white shadow-lg transition hover:-translate-y-1 hover:bg-red-600">Browse more jobs <ArrowRight className="h-5 w-5"/></a></div></div></div></section>
        <section className="bg-slate-50 px-6 py-20"><div className="mx-auto max-w-7xl"><div className="grid gap-6 lg:grid-cols-3">{[[UserCheck, "Recruiter introductions", "Get discovered through a skills-rich member profile and curated community introductions."], [Video, "Live career clinics", "Join CV reviews, interview practice, portfolio feedback, and salary conversations."], [Award, "Credential spotlight", "Showcase PCMO learning, certifications, and verified professional achievements."]].map(([ToolIcon, title, text], index) => { const TIcon = ToolIcon as typeof UserCheck; return <article key={String(title)} className="relative overflow-hidden rounded-2xl bg-white p-8 shadow-sm"><span className="absolute right-5 top-4 font-heading text-6xl font-black text-slate-100">0{index + 1}</span><TIcon className="relative h-10 w-10 text-red-600"/><h3 className="relative mt-6 text-xl font-extrabold text-[#0b3764]">{String(title)}</h3><p className="relative mt-3 leading-7 text-slate-600">{String(text)}</p><Link to="/login?mode=register" className="relative mt-6 inline-flex items-center gap-2 text-sm font-bold text-red-600">Get started <ArrowRight className="h-4 w-4"/></Link></article>})}</div></div></section>
      </>}
      {page === "chat-rooms" && <>
        <section className="px-6 py-20"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-red-600">Live member spaces</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">Choose a room. Bring a real question.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">Focused, moderated conversations for sharing experience, solving problems, and meeting people who understand your work.</p></div><span className="inline-flex items-center gap-2 text-sm font-bold text-emerald-600"><span className="h-2.5 w-2.5 animate-pulse rounded-full bg-emerald-500"/>Community is open</span></div>{communityRooms.isLoading ? <div className="mt-10 grid gap-6 md:grid-cols-2">{[1,2,3,4].map(item => <div key={item} className="h-64 animate-pulse rounded-2xl bg-slate-100"/>)}</div> : <div className="mt-10 grid gap-6 md:grid-cols-2">{communityRooms.data?.rows.map(room => <article key={room.id} className="group relative overflow-hidden rounded-2xl border border-slate-200 bg-white p-7 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-red-200 hover:shadow-xl">{Boolean(room.featured) && <span className="absolute right-5 top-5 rounded-full bg-red-50 px-3 py-1 text-xs font-bold text-red-600">Featured</span>}<div className="grid h-12 w-12 place-items-center rounded-xl bg-[#0b3764] text-white"><MessageCircle className="h-6 w-6"/></div><p className="mt-5 text-xs font-bold uppercase tracking-widest text-red-600">{room.category}</p><h3 className="mt-2 text-2xl font-extrabold text-[#0b3764]">{room.name}</h3><p className="mt-3 min-h-14 leading-7 text-slate-600">{room.description}</p><div className="mt-5 flex flex-wrap gap-4 border-t pt-5 text-xs text-slate-500"><span className="flex items-center gap-1.5"><Users className="h-4 w-4"/>{room.participant_count} participants</span><span className="flex items-center gap-1.5"><MessageCircle className="h-4 w-4"/>{room.message_count} messages</span><span className="flex items-center gap-1.5"><ShieldCheck className="h-4 w-4"/>{room.moderator_name}</span></div><Link to={user ? `/community/chat/${room.slug}` : `/login?redirect=${encodeURIComponent(`/community/chat/${room.slug}`)}`} className="mt-6 flex items-center justify-center gap-2 rounded-lg bg-[#0b3764] px-5 py-3 font-bold text-white transition hover:bg-red-600">{user ? "Enter room" : "Sign in to join"}<ArrowRight className="h-4 w-4"/></Link></article>)}</div>}</div></section>
        <section className="bg-[#071f3b] px-6 py-16 text-white"><div className="mx-auto grid max-w-6xl gap-8 md:grid-cols-3">{[[ShieldCheck,"Expert moderation","PCMO moderators keep discussions relevant, respectful, and useful."],[MessageCircle,"Focused conversations","Topic rooms reduce noise and help members find practical answers faster."],[Users,"Professional belonging","Build recognition and relationships through consistent, generous participation."]].map(([ChatIcon,title,text]) => { const CIcon=ChatIcon as typeof Users; return <div key={String(title)} className="rounded-2xl border border-white/10 bg-white/5 p-7"><CIcon className="h-9 w-9 text-red-400"/><h3 className="mt-5 text-xl font-bold">{String(title)}</h3><p className="mt-3 leading-7 text-white/60">{String(text)}</p></div>})}</div></section>
      </>}
      {page === "conversation" && <>
        <section className="relative overflow-hidden px-6 py-24"><div className="absolute inset-0 bg-gradient-to-b from-white via-red-50/30 to-white"/><div className="relative mx-auto max-w-7xl"><div className="mx-auto max-w-3xl text-center"><span className="inline-flex items-center gap-2 rounded-full bg-red-50 px-4 py-2 text-xs font-bold uppercase tracking-widest text-red-600"><Sparkles className="h-4 w-4"/>Choose how you participate</span><h2 className="mt-5 font-heading text-4xl font-extrabold text-[#0b3764] md:text-5xl">Every valuable conversation starts with one useful contribution.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Ask, answer, share, or listen—there is more than one way to become part of the PCMO community.</p></div><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{[
          [PenLine,"Ask the community","Bring a delivery challenge, career question, or professional decision to experienced peers.","Ask a question"],
          [Lightbulb,"Share an insight","Turn a lesson learned, useful framework, or field experience into value for others.","Create a post"],
          [Mic2,"Lead a discussion","Propose a roundtable topic or facilitate a focused conversation in your area of expertise.","Propose a topic"],
          [HeartHandshake,"Support a peer","Answer questions, welcome new members, and help strengthen a culture of professional generosity.","View discussions"],
        ].map(([PathIcon,title,text,label],index) => { const PIcon=PathIcon as typeof PenLine; return <article key={String(title)} className="group relative overflow-hidden rounded-2xl border border-slate-200 bg-white p-7 shadow-sm transition duration-500 hover:-translate-y-3 hover:border-red-200 hover:shadow-2xl"><span className="absolute right-5 top-3 font-heading text-7xl font-black text-slate-50 transition group-hover:text-red-50">0{index+1}</span><div className="relative grid h-12 w-12 place-items-center rounded-xl bg-[#0b3764] text-white transition duration-300 group-hover:rotate-6 group-hover:bg-red-600"><PIcon className="h-6 w-6"/></div><h3 className="relative mt-6 text-xl font-extrabold text-[#0b3764]">{String(title)}</h3><p className="relative mt-3 min-h-24 text-sm leading-7 text-slate-600">{String(text)}</p><Link to={user ? "/community-profile" : "/login?mode=register"} className="relative mt-5 inline-flex items-center gap-2 text-sm font-bold text-red-600">{String(label)}<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></Link></article>})}</div></div></section>
        <section className="bg-[#071f3b] px-6 py-24 text-white"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-red-400">Featured conversation</p><h2 className="mt-4 font-heading text-4xl font-extrabold md:text-5xl">A question worth exploring together.</h2><blockquote className="relative mt-8 rounded-3xl border border-white/10 bg-white/5 p-8 backdrop-blur"><Quote className="absolute right-7 top-6 h-12 w-12 text-red-400/20"/><p className="relative text-xl font-semibold leading-9">“{conversations.data?.featured?.title || "A new featured community conversation is coming soon."}”</p><div className="mt-7 flex items-center gap-4"><div className="grid h-11 w-11 place-items-center rounded-full bg-red-600 font-bold">PC</div><div><p className="font-bold">PCMO Community Prompt</p><p className="text-xs text-white/45">{Number(conversations.data?.featured?.contributor_count || 1)} contributors · {Number(conversations.data?.featured?.reply_count || 0)} replies</p></div></div></blockquote><Link to={user && conversations.data?.featured ? `/community/post/${conversations.data.featured.id}` : user ? "/community-profile" : "/login?mode=register"} className="mt-8 inline-flex items-center gap-2 rounded bg-red-600 px-6 py-4 font-bold transition hover:-translate-y-1 hover:bg-red-700">Add your perspective <ArrowRight className="h-5 w-5"/></Link></div><div className="rounded-3xl border border-white/10 bg-white/5 p-8"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><TrendingUp className="h-6 w-6 text-red-400"/><h3 className="text-xl font-bold">Trending now</h3></div><span className="flex items-center gap-2 text-xs text-emerald-400"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400"/>Live topics</span></div><div className="mt-7 space-y-3">{conversations.isLoading ? [1,2,3,4,5].map(item => <div key={item} className="h-20 animate-pulse rounded-xl bg-white/5"/>) : conversations.data?.trending.slice(0,5).map((topic,index) => <Link key={topic.id} to={user ? `/community/post/${topic.id}` : "/login?mode=register"} className="group flex items-center gap-4 rounded-xl border border-white/5 bg-white/5 p-4 transition hover:border-red-400/40 hover:bg-white/10"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-white/5 text-sm font-bold text-red-400">{index+1}</span><div className="min-w-0 flex-1"><p className="font-semibold">{topic.title}</p><p className="mt-1 text-xs text-white/40">{Number(topic.contributor_count)} contributors · {Number(topic.reply_count)} replies</p></div><ArrowRight className="h-4 w-4 text-white/30 transition group-hover:translate-x-1 group-hover:text-red-400"/></Link>)}</div></div></div></section>
        <section className="px-6 py-20"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-red-600">Better conversations</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">A professional space built on trust.</h2><p className="mt-5 leading-8 text-slate-600">The strongest communities are not the loudest. They are the ones where members feel safe asking thoughtful questions and confident that responses will be constructive.</p><div className="mt-7 flex flex-wrap gap-2">{["#ProjectControls","#ContractManagement","#Leadership","#Careers","#PMO","#LessonsLearned"].map(tag => <span key={tag} className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-600"><Hash className="h-3 w-3 text-red-600"/>{tag.slice(1)}</span>)}</div></div><div className="grid gap-4 sm:grid-cols-2">{[[ShieldCheck,"Respect expertise","Challenge ideas constructively while respecting the experience behind them."],[Users,"Include every stage","Make room for students, emerging professionals, specialists, and leaders."],[CheckCircle2,"Share responsibly","Protect confidential information and distinguish experience from formal advice."],[HeartHandshake,"Give before asking","Offer context, encouragement, and useful follow-up—not only quick answers."]].map(([ValueIcon,title,text]) => { const VIcon=ValueIcon as typeof ShieldCheck; return <article key={String(title)} className="rounded-2xl border border-slate-200 p-6 transition hover:border-red-200 hover:shadow-lg"><VIcon className="h-8 w-8 text-red-600"/><h3 className="mt-4 text-lg font-bold text-[#0b3764]">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{String(text)}</p></article>})}</div></div></div></section>
        <section className="overflow-hidden bg-gradient-to-r from-red-600 to-red-700 px-6 py-16 text-white"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-8 text-center md:flex-row md:text-left"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-white/60">Your experience has value</p><h2 className="mt-3 font-heading text-3xl font-extrabold md:text-4xl">Don’t just follow the conversation. Shape it.</h2><p className="mt-3 max-w-2xl text-white/70">Join PCMO members exchanging practical knowledge across projects, contracts, careers, and leadership.</p></div><Link to={user ? "/community-profile" : "/login?mode=register"} className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-white px-7 py-4 font-bold text-red-600 shadow-xl transition hover:-translate-y-1">{user ? "Open community" : "Join the conversation"}<ArrowRight className="h-5 w-5"/></Link></div></section>
      </>}
      <section className="bg-slate-50 px-6 py-16"><div className="mx-auto grid max-w-6xl gap-8 rounded-3xl bg-[#0b3764] p-8 text-white shadow-2xl md:grid-cols-[1fr_auto] md:items-center md:p-12"><div><h2 className="font-heading text-3xl font-extrabold">Ready to take part?</h2><p className="mt-3 max-w-2xl leading-7 text-white/70">Create your PCMO account to connect with members, join discussions, and make the most of every networking opportunity.</p><div className="mt-5 flex flex-wrap gap-5 text-sm text-white/80">{["Professional community", "Shared knowledge", "Global connections"].map(item => <span key={item} className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-red-400"/>{item}</span>)}</div></div><Link to="/login?mode=register" className="inline-flex items-center justify-center gap-2 rounded bg-red-600 px-6 py-4 font-bold hover:bg-red-700">Join PCMO <ArrowRight className="h-5 w-5"/></Link></div></section>
    </main><PublicFooter/>
  </div>;
};

export default NetworkingPage;
