import { ArrowRight, Award, BarChart3, BookOpenCheck, BriefcaseBusiness, Building2, CheckCircle2, ChevronDown, ClipboardCheck, FileSearch, Globe2, GraduationCap, Handshake, Lightbulb, Network, Scale, ShieldCheck, Sparkles, Target, Users } from "lucide-react";
import { Link } from "react-router-dom";
import PublicFooter from "@/components/PublicFooter";
import PublicNavigation from "@/components/PublicNavigation";

const solutions = [
  [Users,"Team and corporate membership","Provide structured access to learning, resources, webinars, events, communities, certifications, and development pathways with appropriate organisational administration.","/pages/group_membership","Explore group membership"],
  [GraduationCap,"Workforce capability development","Build role-based pathways across project delivery, controls, contracts, commercial practice, governance, leadership, digital practice, and professional behaviours.","/pages/learning","Explore learning"],
  [Award,"Certification programmes","Align relevant PCMO certification pathways with roles, experience, development plans, professional recognition, and continuing competence.","/pages/certifications","View certifications"],
  [BookOpenCheck,"Standards and practice improvement","Use PCMO standards, guides, templates, publications, research, and assurance thinking to strengthen controlled professional practice.","/pages/standards","Explore standards"],
  [BriefcaseBusiness,"Talent and career partnership","Connect with relevant professionals, support employability and career development, contribute opportunities, and strengthen organisational capability pipelines.","/pages/job_community","Open job community"],
  [Network,"Events and community engagement","Host or support forums, roundtables, webinars, networking, expert exchanges, professional discussions, and cross-sector knowledge sharing.","/pages/upcoming_networking_events","Explore events"],
  [Lightbulb,"Research and thought leadership","Collaborate on evidence, surveys, case studies, working groups, publications, future-practice questions, and responsible professional innovation.","/pages/thought_leadership","Explore thought leadership"],
  [Handshake,"Strategic partnership and sponsorship","Propose a transparent partnership with clear audience value, responsibilities, governance, brand controls, interests, measures, and responsible outcomes.","/contact","Discuss partnership"],
] as const;

const lifecycle = [
  ["01","Define the organisational need","Clarify strategy, target roles, capability gaps, performance needs, audience, geography, operating context, constraints, risks, and intended outcomes."],
  ["02","Assess current capability","Review role expectations, experience, learning history, credentials, performance evidence, systems, controls, behaviours, and development priorities."],
  ["03","Design the pathway","Select membership, learning, certification, standards, resources, events, mentoring, community, research, and reporting components appropriate to the need."],
  ["04","Agree governance","Confirm sponsorship, administrators, participant data, access, eligibility, responsibilities, approvals, support, communications, escalation, and review."],
  ["05","Mobilise and engage","Onboard participants, assign pathways, communicate purpose, provide manager support, remove access barriers, and monitor early participation."],
  ["06","Measure and improve","Evaluate engagement, completion, assessment, application, workplace evidence, stakeholder feedback, capability movement, and the next improvement cycle."],
] as const;

const outcomes = [
  [Target,"Role clarity","Connect job responsibilities, authority, competence, learning, certification, and evidence requirements."],
  [BarChart3,"Capability visibility","Understand participation, development progress, achievement, gaps, and areas requiring organisational support."],
  [Scale,"Integrated practice","Strengthen the connection between project delivery, contracts, commercial decisions, governance, risk, and professional conduct."],
  [ShieldCheck,"Controlled assurance","Support clearer expectations, reliable records, proportionate review, ethical escalation, and evidence of improvement."],
  [Users,"Retention and mobility","Help professionals see credible development pathways, broaden responsibility, receive recognition, and build career confidence."],
  [Globe2,"Shared professional language","Create a more consistent approach across teams, disciplines, locations, suppliers, partners, and leadership levels."],
] as const;

const governance = [
  ["Executive sponsor","Owns the business purpose, organisational commitment, key decisions, barriers, and review of outcomes."],
  ["Programme administrator","Coordinates participant data, access, enrolment, communication, reporting, support, and controlled changes."],
  ["Line managers","Connect development with work, provide feedback and opportunity, review application, and avoid treating completion as competence by itself."],
  ["Participants","Engage honestly, protect information, complete agreed activities, apply learning carefully, retain evidence, and request support."],
  ["PCMO","Provides agreed services, content, systems, support, quality controls, records, reporting, and professional-practice boundaries."],
  ["Assurance stakeholders","Review whether the programme is relevant, controlled, accessible, effective, and producing evidence of intended outcomes."],
] as const;

const faqs = [
  ["Which organisations can work with PCMO?","Private companies, public bodies, educational institutions, professional communities, charities, project owners, contractors, consultants, suppliers, employers, research bodies, and industry partners may enquire where the proposed activity aligns with PCMO's scope and standards."],
  ["What is the difference between team and corporate membership?","Team membership is designed for smaller groups with shared development goals. Corporate membership supports larger organisational cohorts requiring broader administration, analytics, pathways, and priority coordination. Confirm current capacity and features in the membership offer."],
  ["Can programmes be aligned with our competency framework?","PCMO can discuss mapping relevant learning, certification, standards, and resources to defined roles and capability expectations. Mapping does not automatically certify organisational compliance or individual competence."],
  ["Can administrators see participant progress?","Approved organisational reporting may include agreed access, participation, completion, achievement, and pathway information. Visibility must follow the programme agreement, applicable privacy requirements, and appropriate role-based access."],
  ["Can PCMO develop custom or branded learning?","Customisation may be considered where scope, evidence, intellectual property, review, branding, data, delivery, assessment, maintenance, cost, and responsibilities are agreed."],
  ["Can our employees earn PCMO certifications?","Eligible participants can follow the relevant certification requirements. Organisational sponsorship or training does not guarantee eligibility, assessment success, certification, or renewal."],
  ["Can we sponsor an event, publication, or research project?","Yes, where sponsorship is transparent, professionally appropriate, and governed so that commercial support does not improperly control evidence, conclusions, assessment, standards, or participant treatment."],
  ["Can we advertise roles or meet candidates?","Career and networking collaboration may be available. Opportunities, organisational representation, role requirements, compensation information, data collection, and recruitment communications must be accurate and responsible."],
  ["How is organisational data protected?","The engagement should define data categories, purpose, lawful handling, access, retention, security, reporting, subprocessors, incident response, and deletion. Do not provide unnecessary confidential or personal information during an initial enquiry."],
  ["Who owns jointly developed materials?","Ownership, licences, background intellectual property, contributor rights, branding, confidentiality, publication, maintenance, withdrawal, and reuse must be agreed before development begins."],
  ["How do we measure return on investment?","Use a balanced evaluation covering participation, learning, assessment, workplace application, control improvement, manager evidence, performance indicators, retention, mobility, risk, and stakeholder outcomes—not completion counts alone."],
  ["How do we begin?","Send the organisational context, audience, locations, approximate cohort size, roles, capability need, desired outcomes, timing, existing frameworks, decision process, and relevant constraints through the contact pathway."],
] as const;

const OrganizationsHub = () => <div className="min-h-screen bg-white text-slate-800"><PublicNavigation active="connect"/><main>
  <section className="relative overflow-hidden bg-[#071f3b] px-6 py-24 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(220,38,38,.3),transparent_35%)]"/><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.22em] text-red-300">PCMO for organisations</p><h1 className="mt-4 font-heading text-5xl font-extrabold leading-tight md:text-6xl">Build capability that works across projects and contracts.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/70">Connect membership, learning, certification, standards, resources, events, research, talent, and professional community into a controlled organisational development pathway.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/pages/group_membership" className="inline-flex items-center gap-2 rounded bg-red-600 px-6 py-3 font-bold"><Building2 className="h-4 w-4"/>Explore organisation membership</Link><Link to="/contact" className="rounded border border-white/25 px-6 py-3 font-bold">Discuss your requirements</Link></div></div><div className="rounded-3xl border border-white/10 bg-white/5 p-8 backdrop-blur"><Building2 className="h-14 w-14 text-red-400"/><h2 className="mt-6 text-2xl font-extrabold">An integrated capability ecosystem</h2><div className="mt-6 grid grid-cols-2 gap-3">{["Membership","Learning","Certification","Standards","Community","Analytics"].map(item => <div key={item} className="rounded-xl bg-white/5 p-4 text-sm font-bold text-white/75">{item}</div>)}</div></div></div></section>
  <section className="mx-auto max-w-7xl px-6 py-20"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-red-600">Organisation solutions</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">Choose the right route to organisational value</h2></div><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{solutions.map(([Icon,title,text,href,label]) => <article key={title} className="group flex flex-col rounded-2xl border p-7 shadow-sm transition hover:-translate-y-1 hover:border-red-300 hover:shadow-xl"><div className="grid h-12 w-12 place-items-center rounded-xl bg-[#0b3764] text-white group-hover:bg-red-600"><Icon className="h-6 w-6"/></div><h3 className="mt-5 text-xl font-extrabold text-[#0b3764]">{title}</h3><p className="mt-3 flex-1 leading-7 text-slate-600">{text}</p><Link to={href} className="mt-6 inline-flex items-center gap-2 font-bold text-red-600">{label}<ArrowRight className="h-4 w-4"/></Link></article>)}</div></section>
  <section className="bg-[#0b3764] px-6 py-20 text-white"><div className="mx-auto max-w-7xl"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-red-300">Implementation lifecycle</p><h2 className="mt-3 font-heading text-4xl font-extrabold">From business need to measurable improvement</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{lifecycle.map(([number,title,text]) => <article key={number} className="rounded-2xl border border-white/10 bg-white/5 p-7"><span className="text-4xl font-black text-red-400">{number}</span><h3 className="mt-3 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-white/65">{text}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-6 py-20"><div className="text-center"><Sparkles className="mx-auto h-11 w-11 text-red-600"/><h2 className="mt-4 font-heading text-4xl font-extrabold text-[#0b3764]">Outcomes worth measuring</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{outcomes.map(([Icon,title,text]) => <article key={title} className="rounded-2xl border bg-slate-50 p-7"><Icon className="h-9 w-9 text-red-600"/><h3 className="mt-5 text-xl font-bold text-[#0b3764]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></section>
  <section className="bg-red-50 px-6 py-20"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><ShieldCheck className="h-12 w-12 text-red-600"/><h2 className="mt-5 font-heading text-4xl font-extrabold text-[#0b3764]">Governance and accountability</h2><p className="mt-5 leading-8 text-slate-600">Sustainable capability development needs visible sponsorship, appropriate access, reliable administration, manager involvement, participant responsibility, and evidence-led review.</p></div><div className="grid gap-4 sm:grid-cols-2">{governance.map(([role,text]) => <article key={role} className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="text-lg font-bold text-[#0b3764]">{role}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></div></section>
  <section className="mx-auto max-w-4xl px-6 py-20"><h2 className="text-center font-heading text-4xl font-extrabold text-[#0b3764]">Organisation FAQs</h2><div className="mt-10 space-y-4">{faqs.map(([question,answer]) => <details key={question} className="group rounded-xl border bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5 font-bold text-[#0b3764]">{question}<ChevronDown className="h-5 w-5 shrink-0 transition group-open:rotate-180"/></summary><p className="border-t px-5 py-5 leading-7 text-slate-600">{answer}</p></details>)}</div></section>
  <section className="bg-red-600 px-6 py-16 text-center text-white"><Handshake className="mx-auto h-11 w-11"/><h2 className="mt-4 font-heading text-4xl font-extrabold">Start an organisational conversation</h2><p className="mx-auto mt-4 max-w-2xl text-white/80">Share the audience, capability need, intended outcomes, approximate cohort, locations, timing, and governance requirements.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link to="/contact" className="rounded bg-white px-6 py-3 font-bold text-red-600">Contact PCMO</Link><Link to="/pages/group_membership" className="rounded border border-white/40 px-6 py-3 font-bold">Compare organisation options</Link></div></section>
</main><PublicFooter/></div>;

export default OrganizationsHub;
