import { ArrowRight, Award, BookOpen, CalendarDays, CheckCircle2, ChevronDown, Clock3, Download, FileText, Globe2, Headphones, MessageCircleQuestion, MonitorPlay, PlayCircle, Presentation, ShieldCheck, Sparkles, Users, Video } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import PublicFooter from "@/components/PublicFooter";
import PublicNavigation from "@/components/PublicNavigation";
import { useAuth } from "@/hooks/useAuth";
import { api } from "@/lib/api";

const programmes = [
  [Presentation, "Project delivery masterclasses", "Planning, controls, governance, assurance, recovery, benefits, stakeholder leadership, and programme integration."],
  [FileText, "Contracts in practice", "Strategy, formation, administration, notices, records, change, claims, payment, negotiation, and closeout."],
  [ShieldCheck, "Standards and professional practice", "Ethics, accountability, evidence, competence, responsible decisions, and practical application of standards."],
  [Sparkles, "Future practice briefings", "Responsible AI, data, digital controls, sustainability, new delivery models, emerging risks, and innovation."],
  [Award, "Certification clinics", "Pathway selection, eligibility, preparation, assessment expectations, evidence, renewal, and continuing development."],
  [Users, "Career and leadership forums", "Professional pathways, capability building, mentoring, influence, commercial awareness, and leadership through uncertainty."],
] as const;

const featured = [
  ["LIVE MASTERCLASS", "Building a decision-useful integrated project forecast", "Project Controls", "90 min", "Understand forecast evidence, confidence, scenarios, corrective action, and executive decision requirements."],
  ["PRACTICE CLINIC", "Contract notices: timing, content, records, and response", "Contract Management", "75 min", "Work through notice controls, factual drafting, contractual basis, supporting records, response pathways, and common failure points."],
  ["LEADERSHIP FORUM", "Sponsor decisions before delivery pressure becomes delay", "Governance", "60 min", "Clarify outcomes, authority, tolerances, escalation, risk appetite, benefits ownership, and timely governance decisions."],
  ["FUTURE PRACTICE", "Governing responsible AI in project and contract teams", "Digital Practice", "75 min", "Establish approved uses, protected information, validation, human review, records, bias controls, and escalation."],
] as const;

const seriesOneVideos = [
  ["01", "Why Project Management and Contracts Management Must Work Together", "All professionals", "1:53", "01-pm-and-contracts-together.mp4", ["Why projects fail", "PM vs CM silos", "Integrated delivery model", "Future PM-CM professionals"]],
  ["02", "The Complete Project Lifecycle Explained", "Beginners", "1:58", "02-complete-project-lifecycle.mp4", ["Initiation", "Planning", "Execution", "Monitoring and control", "Closeout"]],
  ["03", "Building Successful Projects Through Effective Scope Management", "Project and contract professionals", "1:44", "03-effective-scope-management.mp4", ["Scope definition", "Work breakdown structure", "Scope creep", "Scope control"]],
  ["04", "Project Scheduling Masterclass", "Project controls and delivery professionals", "1:44", "04-project-scheduling-masterclass.mp4", ["Critical path method", "Float", "Baselines", "Recovery schedules"]],
  ["05", "Cost Control and Commercial Awareness for Project Professionals", "Project, controls, and commercial teams", "1:46", "05-cost-control-commercial-awareness.mp4", ["Budgeting", "Forecasting", "Earned value management", "Commercial decisions"]],
  ["06", "Risk Management That Actually Works", "All project and contract professionals", "1:47", "06-risk-management-that-works.mp4", ["Risk registers", "Risk ownership", "Risk responses", "Practical application"]],
] as const;

const journey = [
  ["01", "Select deliberately", "Choose a session that supports a current responsibility, professional objective, certification pathway, or capability gap."],
  ["02", "Prepare", "Review the session outcomes, speaker profile, prerequisites, time zone, technology requirements, and any pre-reading."],
  ["03", "Participate", "Join on time, test claims against your context, use polls and exercises, and ask concise, professionally relevant questions."],
  ["04", "Consolidate", "Download available slides, transcript, workbook, references, or recording and capture the most relevant lessons."],
  ["05", "Apply", "Convert insight into a proportionate workplace action, discussion, experiment, control improvement, or development objective."],
  ["06", "Record development", "Document the activity, learning outcome, application, evidence, and reflection in your professional development record."],
] as const;

const resources = [
  [PlayCircle, "On-demand recordings", "Revisit selected sessions with chaptered recordings and clear access periods."],
  [FileText, "Transcripts and summaries", "Use accessible written content to review key concepts, examples, questions, and conclusions."],
  [Download, "Practical downloads", "Apply companion checklists, templates, workbooks, reference sheets, and implementation prompts."],
  [BookOpen, "Further reading", "Continue into PCMO standards, publications, research, learning pathways, and carefully selected references."],
] as const;

const quality = [
  ["Relevant expertise", "Speakers must demonstrate credible knowledge, experience, research, responsibility, or professional contribution relevant to the topic."],
  ["Clear learning outcomes", "Each webinar identifies what participants should understand, evaluate, practise, or apply after the session."],
  ["Evidence and context", "Claims, experience, opinion, uncertainty, jurisdiction, sector, scale, and limitations should be distinguishable."],
  ["Professional integrity", "Confidential, privileged, personal, commercially restricted, or client-sensitive information must be protected."],
  ["Accessible participation", "Delivery should support clear language, readable materials, questions, appropriate pacing, and inclusive professional discussion."],
  ["Responsible application", "Webinars support learning and do not replace governing contracts, law, organisational authority, standards, or specialist advice."],
] as const;

const faqs = [
  ["How do I register for a PCMO webinar?", "Sign in to the student or member panel, open Webinars, select an available session, and choose Register. Your dashboard will show the registration status and joining information when published."],
  ["Are webinars available to free members?", "Selected sessions and recordings may be open to free members. Specialist masterclasses, certification clinics, extended recordings, or companion resources may require an eligible membership or enrolment."],
  ["Where will I find the joining link?", "For a registered live webinar, the joining link is displayed in the member webinar area when released. Check the session time zone and return shortly before the scheduled start."],
  ["Will a recording be available?", "Recording depends on speaker permission, confidentiality, production quality, and programme requirements. When available, it appears in Webinars or the Library with its access conditions."],
  ["Can I download slides, transcripts, or workbooks?", "Available companion files are attached to the webinar or its Library resource. Access and download permissions follow the membership, enrolment, copyright, and reuse conditions shown."],
  ["Do webinars count toward continuing professional development?", "A relevant webinar may support a professional development record when you document participation, learning, reflection, and application. Any claimed credit remains subject to the rules of the certification or professional body concerned."],
  ["Can I ask the speaker a question?", "Live sessions may include moderated questions, polls, exercises, or discussion. Keep questions concise, relevant, respectful, and free of confidential or identifying information."],
  ["What if I miss a registered webinar?", "Check the webinar area for a recording, transcript, summary, or related resource. Availability is not guaranteed, so cancel in advance when possible if you cannot attend."],
  ["How can I propose a webinar topic or speaker?", "Send PCMO the professional question, intended audience, learning value, speaker credentials, proposed format, evidence base, conflicts, sponsorship, and any confidentiality restrictions."],
  ["Can webinar content be reused?", "Personal learning notes and short attributed references may be permitted, but recording, redistribution, substantial reproduction, commercial reuse, or derivative publication requires permission unless explicitly licensed."],
] as const;

const WebinarsHubContent = () => <div className="min-h-screen bg-white text-slate-800"><PublicNavigation active="resources"/><main>
  <section className="relative overflow-hidden bg-[#071f3b] px-6 py-24 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_22%,rgba(220,38,38,.3),transparent_35%)]"/><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.08fr_.92fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.22em] text-red-300">PCMO Webinars</p><h1 className="mt-4 font-heading text-5xl font-extrabold leading-tight md:text-6xl">Expert-led learning for decisions that matter.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/70">Join live masterclasses, practical clinics, leadership forums, certification briefings, and on-demand sessions across project and contract management.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/webinars" className="inline-flex items-center gap-2 rounded bg-red-600 px-6 py-3 font-bold"><CalendarDays className="h-4 w-4"/>Open member webinars</Link><a href="#featured" className="rounded border border-white/25 px-6 py-3 font-bold">Explore programme</a></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-white/65"><span className="flex items-center gap-2"><Globe2 className="h-4 w-4 text-red-300"/>Online access</span><span className="flex items-center gap-2"><MessageCircleQuestion className="h-4 w-4 text-red-300"/>Live questions</span><span className="flex items-center gap-2"><PlayCircle className="h-4 w-4 text-red-300"/>Selected recordings</span></div></div><div className="relative rounded-3xl border border-white/10 bg-white/5 p-8 backdrop-blur"><div className="rounded-2xl bg-white p-7 text-slate-800"><div className="flex items-center justify-between"><span className="rounded-full bg-red-50 px-3 py-1 text-xs font-bold text-red-600">ADVANCED LEARNING</span><Video className="h-9 w-9 text-[#0b3764]"/></div><h2 className="mt-6 text-2xl font-extrabold text-[#0b3764]">From insight to application</h2><p className="mt-3 leading-7 text-slate-600">Every strong webinar connects credible expertise, clear outcomes, contextual judgement, professional discussion, and a practical next step.</p><div className="mt-6 grid grid-cols-3 gap-3 text-center"><div className="rounded-xl bg-slate-50 p-3"><MonitorPlay className="mx-auto h-5 w-5 text-red-600"/><p className="mt-2 text-xs font-bold">Live</p></div><div className="rounded-xl bg-slate-50 p-3"><Headphones className="mx-auto h-5 w-5 text-red-600"/><p className="mt-2 text-xs font-bold">On demand</p></div><div className="rounded-xl bg-slate-50 p-3"><FileText className="mx-auto h-5 w-5 text-red-600"/><p className="mt-2 text-xs font-bold">Resources</p></div></div></div></div></div></section>

  <section className="mx-auto max-w-7xl px-6 py-20"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-red-600">Professional programme</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">Learning across the profession</h2><p className="mx-auto mt-4 max-w-3xl leading-7 text-slate-600">Move from technical controls to commercial practice, leadership, certification, standards, and emerging professional questions.</p></div><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{programmes.map(([Icon,title,text]) => <article key={title} className="group rounded-2xl border p-7 shadow-sm transition hover:-translate-y-1 hover:border-red-300 hover:shadow-xl"><div className="grid h-12 w-12 place-items-center rounded-xl bg-[#0b3764] text-white group-hover:bg-red-600"><Icon className="h-6 w-6"/></div><h3 className="mt-5 text-xl font-extrabold text-[#0b3764]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></section>

  <section className="bg-[#071f3b] px-6 py-20 text-white"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-red-300">Series 1</p><h2 className="mt-3 font-heading text-4xl font-extrabold">Project Management Fundamentals</h2><p className="mt-4 max-w-3xl leading-7 text-white/65">Six original PCMO narrated video briefings connecting fundamental project controls with contract and commercial awareness.</p></div><span className="rounded-full border border-white/15 px-4 py-2 text-sm font-bold text-white/75">6 videos · approximately 11 minutes</span></div><div className="mt-12 grid gap-7 lg:grid-cols-2">{seriesOneVideos.map(([number,title,audience,duration,file,topics]) => <article key={number} className="overflow-hidden rounded-2xl border border-white/10 bg-white/5"><video controls preload="metadata" className="aspect-video w-full bg-black" aria-label={title}><source src={`/webinars/series-1/${file}`} type="video/mp4"/>Your browser does not support HTML5 video.</video><div className="p-6"><div className="flex flex-wrap items-center gap-2 text-xs font-bold uppercase tracking-wider text-red-300"><span>Webinar {number}</span><span className="text-white/25">•</span><span>{duration}</span><span className="text-white/25">•</span><span>{audience}</span></div><h3 className="mt-3 text-xl font-extrabold leading-7">{title}</h3><div className="mt-4 flex flex-wrap gap-2">{topics.map(topic => <span key={topic} className="rounded-full bg-white/10 px-3 py-1 text-xs text-white/70">{topic}</span>)}</div><div className="mt-5 flex flex-wrap gap-3"><a href={`/webinars/series-1/${file}`} download className="inline-flex items-center gap-2 rounded border border-red-300/30 px-4 py-2 text-sm font-bold text-red-300 transition hover:border-white/40 hover:text-white"><Download className="h-4 w-4"/>Download MP4</a><a href={`/webinars/series-1/${file.replace(".mp4", "-video-script.txt")}`} download className="inline-flex items-center gap-2 rounded bg-white px-4 py-2 text-sm font-bold text-[#0b3764] transition hover:bg-red-50"><FileText className="h-4 w-4"/>Download video script</a></div></div></article>)}</div><div className="mt-10 rounded-2xl border border-red-400/25 bg-red-500/10 p-7 sm:flex sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-red-300">Series 1 lead magnet</p><h3 className="mt-2 text-2xl font-extrabold">Integrated PM-CM Career Roadmap</h3><p className="mt-2 text-white/65">Map delivery, controls, contract, commercial, leadership, and professional development capabilities.</p></div><Link to="/library" className="mt-5 inline-flex shrink-0 items-center gap-2 rounded bg-red-600 px-5 py-3 font-bold sm:mt-0">Open Library<ArrowRight className="h-4 w-4"/></Link></div></div></section>

  <section id="featured" className="bg-slate-50 px-6 py-20"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-red-600">Featured webinar tracks</p><h2 className="mt-3 font-heading text-4xl font-extrabold text-[#0b3764]">Sessions built around real professional decisions</h2></div><Link to="/webinars" className="inline-flex items-center gap-2 font-bold text-red-600">View live availability<ArrowRight className="h-4 w-4"/></Link></div><div className="mt-10 grid gap-6 lg:grid-cols-2">{featured.map(([format,title,category,duration,text],index) => <article key={title} className="rounded-2xl border bg-white p-7 shadow-sm"><div className="flex items-start gap-5"><div className="grid h-16 w-16 shrink-0 place-items-center rounded-full bg-[#0b3764] text-white"><PlayCircle className="h-8 w-8"/></div><div><div className="flex flex-wrap gap-2 text-xs font-bold tracking-wider text-red-600"><span>{format}</span><span className="text-slate-300">•</span><span>{category}</span></div><h3 className="mt-2 text-xl font-extrabold leading-7 text-[#0b3764]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p><p className="mt-4 flex items-center gap-2 text-xs text-slate-500"><Clock3 className="h-4 w-4"/>{duration} · Track {String(index+1).padStart(2,"0")}</p></div></div></article>)}</div></div></section>

  <section className="bg-[#0b3764] px-6 py-20 text-white"><div className="mx-auto max-w-7xl"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-red-300">Webinar journey</p><h2 className="mt-3 font-heading text-4xl font-extrabold">Turn attendance into professional development</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{journey.map(([number,title,text]) => <article key={number} className="rounded-2xl border border-white/10 bg-white/5 p-7"><span className="text-4xl font-black text-red-400">{number}</span><h3 className="mt-3 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-white/65">{text}</p></article>)}</div></div></section>

  <section className="mx-auto max-w-7xl px-6 py-20"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><Download className="h-12 w-12 text-red-600"/><h2 className="mt-5 font-heading text-4xl font-extrabold text-[#0b3764]">Continue after the live session</h2><p className="mt-5 leading-8 text-slate-600">Where rights and programme arrangements permit, PCMO connects webinar learning with recordings, transcripts, practical tools, publications, and structured learning.</p><Link to="/library" className="mt-7 inline-flex items-center gap-2 rounded bg-[#0b3764] px-5 py-3 font-bold text-white">Open the Library<ArrowRight className="h-4 w-4"/></Link></div><div className="grid gap-5 sm:grid-cols-2">{resources.map(([Icon,title,text]) => <article key={title} className="rounded-2xl border bg-slate-50 p-6"><Icon className="h-8 w-8 text-red-600"/><h3 className="mt-4 text-lg font-bold text-[#0b3764]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>

  <section className="bg-red-50 px-6 py-20"><div className="mx-auto max-w-7xl"><div className="text-center"><ShieldCheck className="mx-auto h-12 w-12 text-red-600"/><h2 className="mt-4 font-heading text-4xl font-extrabold text-[#0b3764]">Speaker and content standards</h2><p className="mx-auto mt-4 max-w-3xl leading-7 text-slate-600">Advanced learning depends on credible contribution, transparent context, professional integrity, and careful application.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{quality.map(([title,text]) => <article key={title} className="rounded-2xl bg-white p-6 shadow-sm"><CheckCircle2 className="h-7 w-7 text-emerald-600"/><h3 className="mt-4 text-lg font-bold text-[#0b3764]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>

  <section className="mx-auto max-w-4xl px-6 py-20"><h2 className="text-center font-heading text-4xl font-extrabold text-[#0b3764]">Webinar FAQs</h2><p className="mx-auto mt-4 max-w-2xl text-center leading-7 text-slate-600">Registration, access, recordings, resources, professional development, participation, and responsible reuse.</p><div className="mt-10 space-y-4">{faqs.map(([question,answer]) => <details key={question} className="group rounded-xl border bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5 font-bold text-[#0b3764]">{question}<ChevronDown className="h-5 w-5 shrink-0 transition group-open:rotate-180"/></summary><p className="border-t px-5 py-5 leading-7 text-slate-600">{answer}</p></details>)}</div></section>

<section className="bg-red-600 px-6 py-16 text-center text-white"><Video className="mx-auto h-11 w-11"/><h2 className="mt-4 font-heading text-4xl font-extrabold">Join the next professional conversation</h2><p className="mx-auto mt-4 max-w-2xl text-white/80">Register through your member panel, prepare with purpose, participate actively, and carry the learning into practice.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link to="/webinars" className="rounded bg-white px-6 py-3 font-bold text-red-600">Open member webinars</Link><Link to="/pages/learning" className="rounded border border-white/40 px-6 py-3 font-bold">Explore learning</Link></div></section>
</main><PublicFooter/></div>;
const WebinarAccessNotice = ({ signedIn }: { signedIn: boolean }) => <div className="min-h-screen bg-slate-50 text-slate-800"><PublicNavigation active="resources"/><main className="grid min-h-[calc(100vh-5rem)] place-items-center px-6 py-16"><section className="max-w-xl rounded-3xl border bg-white p-9 text-center shadow-xl"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-[#0b3764] text-white"><Video className="h-8 w-8"/></span><p className="mt-6 text-sm font-bold uppercase tracking-[.18em] text-red-600">Member-only learning</p><h1 className="mt-3 font-heading text-3xl font-extrabold text-[#0b3764]">Unlock PCMO webinars</h1><p className="mt-4 leading-7 text-slate-600">Live webinar registrations, recordings, and downloadable materials are available to active PCMO members only.</p><div className="mt-7 flex flex-wrap justify-center gap-3">{signedIn ? <Link to="/membership" className="rounded bg-red-600 px-6 py-3 font-bold text-white transition hover:bg-red-700">Unlock membership</Link> : <Link to="/login?redirect=%2Fpages%2Fwebinars" className="rounded bg-red-600 px-6 py-3 font-bold text-white transition hover:bg-red-700">Sign in to continue</Link>}<Link to="/pages/membership_packages" className="rounded border border-[#0b3764] px-6 py-3 font-bold text-[#0b3764]">View membership plans</Link></div></section></main><PublicFooter/></div>;
const WebinarsHub = () => { const { user, loading } = useAuth(); const access = useQuery({ queryKey: ["public-webinar-access", user?.id], queryFn: () => api<{ active: boolean }>("/api/webinars/access"), enabled: Boolean(user) }); if (loading || (user && access.isLoading)) return <div className="min-h-screen bg-slate-50"><PublicNavigation active="resources"/><main className="grid min-h-[calc(100vh-5rem)] place-items-center text-slate-500">Checking webinar access?</main></div>; if (!user || !access.data?.active) return <WebinarAccessNotice signedIn={Boolean(user)} />; return <WebinarsHubContent />; };
// Webinar access components are declared after the protected page content.

export default WebinarsHub;
